(function(){
const C=window.RainbowCurriculum;if(!C)return;
const legacyToCurriculum=(a)=>C.aliases[a?.skill]||null;
function states(){const s=C.fromLegacy(data);(data.curriculumStates||{});return {...s,...(data.curriculumStates||{})};}
function state(id){return C.normalizeState(states()[id]||'NOT_INTRODUCED')}
function rank(s){return {REVIEW_NEEDED:0,LEARNING:1,DEVELOPING:2,INTRODUCED:3,NOT_INTRODUCED:4,MOSTLY_MASTERED:5,MASTERED:6}[C.normalizeState(s)]??4}
function activityForSkill(skillId){return activities.filter(a=>legacyToCurriculum(a)===skillId)}
function dueReviewSkills(){const now=Date.now(),out=[];Object.entries(data.evidence||{}).forEach(([k,arr])=>{if(!arr?.length)return;const [domain,name]=k.split('::'),id=C.aliases[name];if(!id)return;const st=state(id),last=new Date(arr.at(-1).date+'T12:00:00').getTime(),days=(now-last)/86400000;let due=Infinity;if(st==='INTRODUCED')due=1;if(st==='LEARNING')due=1;if(st==='DEVELOPING')due=3;if(st==='MOSTLY_MASTERED')due=7;if(st==='MASTERED')due=18;if(st==='REVIEW_NEEDED')due=0;if(days>=due)out.push({id,days,domain,name,st});});return out.sort((a,b)=>a.st==='REVIEW_NEEDED'?-1:b.days-a.days)}
function readinessTarget(){const s=states(),candidates=C.nextCandidates(s).filter(x=>activityForSkill(x.skill_id).length);const reading=candidates.filter(x=>x.domain==='reading').sort((a,b)=>a.difficulty_level-b.difficulty_level)[0];return reading||candidates.sort((a,b)=>a.difficulty_level-b.difficulty_level)[0]||null}
function recentIds(days=3){const cut=Date.now()-days*86400000;return new Set((data.questHistory||[]).filter(x=>new Date(x.date+'T12:00:00').getTime()>=cut).map(x=>x.activityId))}
function chooseAdaptive(domain,mode='priority',exclude=new Set(),types=new Set()){
 let pool=activitiesFor(domain).filter(a=>!exclude.has(a.id));if(!pool.length)return null;const recent=recentIds(2),due=new Set(dueReviewSkills().map(x=>x.id));
 pool.sort((a,b)=>{const ai=legacyToCurriculum(a),bi=legacyToCurriculum(b),as=ai?state(ai):getStatus(a.domain,a.skill),bs=bi?state(bi):getStatus(b.domain,b.skill);let av=rank(as),bv=rank(bs);if(mode==='review'){av=due.has(ai)?-4:av;bv=due.has(bi)?-4:bv}if(mode==='challenge'){av=ai&&C.ready(ai,states())?av-2:av+2;bv=bi&&C.ready(bi,states())?bv-2:bv+2}av+=recent.has(a.id)?2:0;bv+=recent.has(b.id)?2:0;av+=types.has(a.interaction_type)?1:0;bv+=types.has(b.interaction_type)?1:0;return av-bv||(a.difficulty||1)-(b.difficulty||1)});return pool[0];
}
window.makeQuest=function(){
 const picked=[],exclude=new Set(),types=new Set();const target=readinessTarget();
 function add(a){if(!a||exclude.has(a.id))return; picked.push(a.id);exclude.add(a.id);types.add(a.interaction_type)}
 // ~40% priority: literacy/math target work
 if(target){const t=activityForSkill(target.skill_id).find(a=>!exclude.has(a.id));add(t)}else add(chooseAdaptive('reading','priority',exclude,types));
 add(chooseAdaptive(target?.domain==='math'?'reading':'math','priority',exclude,types));
 // ~25% review
 const due=dueReviewSkills().find(x=>activityForSkill(x.id).some(a=>!exclude.has(a.id)));if(due)add(activityForSkill(due.id).find(a=>!exclude.has(a.id)));else add(chooseAdaptive('reading','review',exclude,types));
 // ~20% secondary domain
 const rotation=['language','logic','science','memory','sel','executive','knowledge'];const day=Math.floor(Date.now()/86400000);add(chooseAdaptive(rotation[day%rotation.length],'priority',exclude,types));
 // ~15% challenge/enrichment/movement
 const enrichment=['creativity','gross','fine','life','writing'];add(chooseAdaptive(enrichment[day%enrichment.length],'challenge',exclude,types));
 data.quest=picked.slice(0,5);data.questDate=todayKey();data.questResults={};data.curriculumVersion=C.version;persist(false);renderQuest();
};
function masteryIcon(st){st=C.normalizeState(st);if(st==='MASTERED')return'✓';if(['MOSTLY_MASTERED','DEVELOPING','LEARNING','INTRODUCED','REVIEW_NEEDED'].includes(st))return'◐';return'○'}
function label(st){return C.normalizeState(st).split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ')}
function renderPath(){const parent=document.getElementById('parent');if(!parent)return;let sec=document.getElementById('learningPath');if(!sec){sec=document.createElement('div');sec.id='learningPath';sec.className='card learning-path-card';const tracker=parent.querySelector('#skillTracker')?.closest('.card');tracker?.after(sec)}const stages=['R0','R1','R2','R3','R4','R5','R6','R7','R8','R9','R10'];const reading=C.skills.filter(s=>s.domain==='reading'&&stages.includes(s.stage));const target=readinessTarget();sec.innerHTML=`<div class="path-head"><div><span class="badge adult">🗺️ Learning Path</span><h3>Reading roadmap</h3></div><small>✓ mastered · ◐ learning · ○ coming next</small></div><div class="path-list">${reading.map(s=>`<div class="path-row ${target?.skill_id===s.skill_id?'next-target':''}"><span class="path-icon">${masteryIcon(state(s.skill_id))}</span><div><b>${s.title}</b><small>${label(state(s.skill_id))}${target?.skill_id===s.skill_id?' · Recommended next':''}</small></div></div>`).join('')}</div>`}
function summaryWindow(days){const cut=Date.now()-days*86400000;const h=(data.questHistory||[]).filter(x=>new Date(x.date+'T12:00:00').getTime()>=cut);const sessions=new Set(h.map(x=>x.date));const bySkill={};h.forEach(x=>{const a=activities.find(v=>v.id===x.activityId);if(!a)return;const k=`${a.domain} · ${a.skill}`;(bySkill[k]||(bySkill[k]=[])).push(x)});const stats=Object.entries(bySkill).map(([k,v])=>({k,n:v.length,avg:v.reduce((n,x)=>n+(x.score||0),0)/v.length,hints:v.reduce((n,x)=>n+(x.hints||0),0)/v.length})).sort((a,b)=>b.n-a.n);return{h,sessions,stats}}
function reportText(days){const r=summaryWindow(days);if(!r.h.length)return'No completed learning sessions in this period yet.';const strong=r.stats.filter(x=>x.avg>=.82).slice(0,2),practice=r.stats.filter(x=>x.avg<.72||x.hints>=1.2).slice(0,2),target=readinessTarget();return `${r.sessions.size} learning day${r.sessions.size===1?'':'s'} · ${r.h.length} completed activities. ${strong.length?'Strong/reliable: '+strong.map(x=>x.k).join(', ')+'. ':''}${practice.length?'Developing: '+practice.map(x=>x.k).join(', ')+'. ':''}${target?'Next target: '+target.title+'.':''}`}
function renderReports(){const parent=document.getElementById('parent');if(!parent)return;let sec=document.getElementById('parentReports');if(!sec){sec=document.createElement('div');sec.id='parentReports';sec.className='parent-reports';parent.appendChild(sec)}sec.innerHTML=`<div class="section-title"><h2>📈 Progress Reports</h2><p>Meaningful summaries from actual practice evidence.</p></div><div class="grid thirds"><div class="card compact"><h3>Today</h3><p>${reportText(1)}</p></div><div class="card compact"><h3>This Week</h3><p>${reportText(7)}</p></div><div class="card compact"><h3>This Month</h3><p>${reportText(30)}</p></div></div>`}
function renderWhyNext(){const target=readinessTarget(),el=document.getElementById('nextFocus');if(!el||!target)return;const prereq=target.prerequisites.map(id=>C.byId[id]?.title).filter(Boolean);el.innerHTML=`<b>Next target: ${target.title}</b><br><span>Why: prerequisites ${prereq.length?prereq.join(', '):'for this stage'} show enough readiness, while this skill still needs evidence across multiple examples and sessions.</span>`}
function placementNotice(){const parent=document.getElementById('parent');if(!parent||document.getElementById('placementNotice'))return;const answered=Object.keys(data.answers||{}).length;if(answered>=18)return;const box=document.createElement('div');box.id='placementNotice';box.className='card placement-notice';box.innerHTML='<span class="badge adult">🎯 Placement</span><h3>Short playful placement still recommended</h3><p>Do not start from zero. Use 5–10 minute checkpoints across early sessions to verify sounds, vowels, blending, segmenting, CVC reading/spelling, number sense, patterns, and comprehension.</p><button class="btn mint" onclick="go(\'baseline\')">Continue Reading Placement</button>';parent.prepend(box)}
function style(){if(document.getElementById('adaptiveCss'))return;const s=document.createElement('style');s.id='adaptiveCss';s.textContent='.learning-path-card{margin-top:14px}.path-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.path-head h3{margin:6px 0}.path-head small{color:var(--muted)}.path-list{display:grid;gap:7px;margin-top:12px}.path-row{display:grid;grid-template-columns:34px 1fr;gap:8px;align-items:center;padding:10px 12px;border-radius:16px;background:#faf8fd}.path-row.next-target{background:#fff6d8;box-shadow:inset 0 0 0 2px #ffe180}.path-icon{font-size:21px;font-weight:950;color:#8855b4}.path-row b,.path-row small{display:block}.path-row small{font-size:11px;color:var(--muted);margin-top:2px}.parent-reports{margin-top:18px}.placement-notice{margin-bottom:14px;border-left:5px solid #8fd9c1}.placement-notice h3{margin:7px 0 4px}@media(max-width:700px){.path-head{flex-direction:column}}';document.head.appendChild(s)}
const oldGo=window.go;window.go=function(id){oldGo(id);if(id==='parent')setTimeout(()=>{renderPath();renderReports();renderWhyNext();placementNotice()},30)};
style();
})();