const groups=[
{id:'consonants',title:'A · Consonant sounds',max:10,help:'Show one letter at a time. Ask: “What sound does this letter make?”',items:[['m','/mmmm/'],['s','/ssss/'],['t','short /t/'],['p','short /p/'],['n','/nnnn/'],['c','/k/'],['f','/ffff/'],['r','/r/'],['l','/llll/'],['h','/h/']]},
{id:'vowels',title:'B · Short vowels',max:5,help:'Ask for the short sound, not the letter name.',items:[['a','/ă/ apple'],['i','/ĭ/ igloo'],['o','/ŏ/ octopus'],['e','/ĕ/ egg'],['u','/ŭ/ umbrella']]},
{id:'begin',title:'C · Beginning sounds',max:3,help:'No letters. Ask for the first sound.',items:[['moon','/m/'],['sun','/s/'],['fish','/f/']]},
{id:'end',title:'D · Ending sounds',max:3,help:'Ask for the final sound.',items:[['cat','/t/'],['map','/p/'],['sun','/n/']]},
{id:'blend',title:'E · Oral blending',max:4,help:'Parent says sounds slowly. Child says the whole word.',items:[['/m/ /e/','me'],['/s/ /u/ /n/','sun'],['/m/ /a/ /p/','map'],['/f/ /i/ /sh/','fish']]},
{id:'segment',title:'F · Oral segmenting',max:4,help:'Parent says the word. Child says each sound.',items:[['me','/m/ /ē/'],['map','/m/ /a/ /p/'],['sun','/s/ /u/ /n/'],['cat','/c/ /a/ /t/']]},
{id:'cvc',title:'G · CVC decoding',max:4,help:'Only if blending is going reasonably well. No picture clues.',items:[['mat','decode'],['sit','decode'],['map','decode'],['cat','decode']]}
];
const lesson=[
['Magical introduction','1 min','Invite her into the adventure.','“Luna was flying over Rainbow Valley and five magical sounds fell from her bag! Can you help find them?”'],
['Sound warm-up','2–3 min','No letters. Find words that start the same.','“Which two start the same: moon, mouse, sun?” Then sun/sock/map and pig/pan/tiger.'],
['Teach / review','3–4 min','Model m, s, t, p, a with pure sounds.','m=/mmmm/ · s=/ssss/ · t=short /t/ · p=short /p/ · a=/ă/'],
['Sound treasure hunt','4 min','Hunt household objects by first sound.','“Find something beginning with /ssss/.” Then /mmmm/, /p/, /t/.'],
['Jump to the sound','3 min','Place m,s,t,p cards on the floor.','“Jump to the beginning sound of moon.” Then sun, pig, top.'],
['Robot blending','3 min','Begin blending orally before letters.','Try /ă/ /t/ → at; /ă/ /m/ → am; /m/ /a/ /t/ → mat; /s/ /a/ /t/ → sat.'],
['Word building','2–3 min','Only if oral blending is going reasonably well.','Build m-a-t. Slide under each letter and blend. Change m to s for sat.'],
['Feed the Unicorn','1–2 min','Sort words by first sound.','For /m/: moon, sun, map. For /s/: sock, pig, sun.'],
['Quick review','1 min','Five short prompts without over-helping.','m sound · s sound · first sound in map · first sound in sun · blend /m/ /a/ /t/.'],
['Celebration','1 min','Praise effort and strategy.','“Luna got her rainbow crystal back because you used your Sound Detective ears!”'],
['If she struggles','as needed','Simplify to two sounds and use blocks or toy movement.','Try /m/ /e/ → me or /ă/ /t/ → at. Stop positively if frustration grows.'],
['If it is very easy','1–3 min','Increase thinking rather than dumping in more letters.','Segment mat and sat using one block per phoneme.']
];
const skills=['Letter sounds','Beginning sounds','Ending sounds','Middle / short-vowel sounds','Oral blending','Oral segmenting','CVC reading','CVC spelling','Short vowels','Digraphs','Blends','Heart words','Sentence reading','Decodable story reading'];
const rewards=[['🌈','Rainbow Star'],['💎','Unicorn Gem'],['⭐','Courage Star'],['☁️','Cloud Badge'],['🧩','Blend Builder'],['🔎','Sound Detective'],['🪄','Word Wizard'],['👂','Great Listening'],['💪','Brave Try'],['📖','Reading Spark'],['👑','Castle Crown'],['✨','Magic Spark']];
const games={
feed:[{prompt:'Luna eats /m/ words. Which one?',choices:['moon','sun','pig'],answer:'moon'},{prompt:'Luna eats /s/ words. Which one?',choices:['map','sock','top'],answer:'sock'},{prompt:'Luna eats /p/ words. Which one?',choices:['pan','sun','mat'],answer:'pan'},{prompt:'Luna eats /t/ words. Which one?',choices:['fish','top','map'],answer:'top'}],
gems:[{prompt:'Find the /m/ gem',choices:['moon 🌙','sun ☀️','fish 🐟'],answer:'moon 🌙'},{prompt:'Find the /s/ gem',choices:['pig 🐷','sock 🧦','map 🗺️'],answer:'sock 🧦'},{prompt:'Find the /p/ gem',choices:['pan 🍳','top 🧸','moon 🌙'],answer:'pan 🍳'},{prompt:'Find the /t/ gem',choices:['sun ☀️','top 🧸','map 🗺️'],answer:'top 🧸'}],
blend:[{prompt:'Parent says: /m/ /a/ /t/. Tap the word.',choices:['mat','sat','map'],answer:'mat'},{prompt:'Parent says: /s/ /a/ /t/. Tap the word.',choices:['map','sat','sit'],answer:'sat'},{prompt:'Parent says: /m/ /a/ /p/. Tap the word.',choices:['mat','map','tap'],answer:'map'},{prompt:'Parent says: /ă/ /t/. Tap the word.',choices:['at','am','it'],answer:'at'}]
};
let data=JSON.parse(localStorage.getItem('magicPhonics')||'{}');data.answers=data.answers||{};data.steps=data.steps||{};data.observe=data.observe||{};data.tracker=data.tracker||{};data.rewards=data.rewards||{};data.notes=data.notes||'';data.gameStars=data.gameStars||0;data.theme=data.theme||'unicorn';
function persist(show=true){localStorage.setItem('magicPhonics',JSON.stringify(data));updateStats();if(show)toast()}
function toast(){const t=document.getElementById('toast');t.classList.add('show');clearTimeout(window._t);window._t=setTimeout(()=>t.classList.remove('show'),850)}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='parent'){renderBreakdown();renderNextFocus()}}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function setTheme(t){data.theme=t;document.body.dataset.theme=t;document.getElementById('unicornTheme').classList.toggle('active',t==='unicorn');document.getElementById('princessTheme').classList.toggle('active',t==='princess');document.getElementById('heroArt').textContent=t==='unicorn'?'🦄':'🏰';persist(false)}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderAssessment(){const h=document.getElementById('assessment');h.innerHTML='';groups.forEach(g=>{const c=document.createElement('div');c.className='card';c.style.marginTop='12px';let s=`<div class="kicker">${g.title}</div><h3>${g.help}</h3>`;g.items.forEach((it,i)=>{const k=`${g.id}-${i}`,v=data.answers[k];s+=`<div class="question"><div><div class="qtext">${esc(it[0])}</div><div class="qsub">Expected: ${esc(it[1])}</div></div><div class="score-buttons"><button class="yes ${v===1?'active':''}" onclick="answer('${k}',1)">✓</button><button class="no ${v===0?'active':''}" onclick="answer('${k}',0)">×</button></div></div>`});c.innerHTML=s;h.appendChild(c)});updateScore()}
function answer(k,v){data.answers[k]=v;persist(false);renderAssessment();renderBreakdown()}
function groupScore(id){const g=groups.find(x=>x.id===id);return g.items.reduce((n,_,i)=>n+(data.answers[`${id}-${i}`]===1?1:0),0)}
function total(){return groups.reduce((n,g)=>n+groupScore(g.id),0)}
function stage(){const c=groupScore('consonants'),v=groupScore('vowels'),b=groupScore('blend'),s=groupScore('segment'),r=groupScore('cvc');if(r>=3&&b>=3&&s>=3)return['CVC+','CVC decoding is strong. Focus on spelling, short-vowel contrast, fluency, and early sentences.'];if(c>=7&&v>=3&&b>=3&&s>=3)return['CVC','Ready to connect strong oral skills to written CVC reading and spelling.'];if(c>=7)return['Blend','Sounds are mostly strong. Focus on oral blending and segmenting before pushing more written words.'];return['Foundation','Strengthen automatic consonant and short-vowel sounds, then connect them to beginning sounds.']}
function updateScore(){const n=total();document.getElementById('scoreNow').textContent=n;document.getElementById('scoreBar').style.width=(n/33*100)+'%';document.getElementById('recommendation').textContent=stage()[1]}
function resetBaseline(){if(confirm('Clear the baseline answers?')){data.answers={};persist();renderAssessment();renderBreakdown();renderNextFocus()}}
function renderLesson(){const h=document.getElementById('lessonSteps');h.innerHTML='';lesson.forEach((x,i)=>{const k='step'+i,d=document.createElement('div');d.className='card step';d.innerHTML=`<div class="step-num">${i+1}</div><div><div class="kicker">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p><div class="say">${x[3]}</div><label class="checkline"><input type="checkbox" ${data.steps[k]?'checked':''} onchange="toggleStep('${k}',this.checked)"><span><b>Done</b> — mark when completed or intentionally skipped.</span></label></div>`;h.appendChild(d)})}
function toggleStep(k,v){data.steps[k]=v;persist()}
function renderTracker(){const h=document.getElementById('tracker');h.innerHTML='';skills.forEach((s,i)=>{const k='skill'+i,v=data.tracker[k]||'Not Introduced',r=document.createElement('div');r.className='tracker-row';r.innerHTML=`<b>${s}</b><select class="status-select" onchange="setTrack('${k}',this.value)"><option ${v==='Not Introduced'?'selected':''}>Not Introduced</option><option ${v==='Learning'?'selected':''}>Learning</option><option ${v==='Mostly Knows'?'selected':''}>Mostly Knows</option><option ${v==='Mastered'?'selected':''}>Mastered</option></select>`;h.appendChild(r)})}
function setTrack(k,v){data.tracker[k]=v;persist()}
function renderBreakdown(){const h=document.getElementById('breakdown');h.innerHTML='';groups.forEach(g=>{const d=document.createElement('div');d.className='mini';d.innerHTML=`<b>${groupScore(g.id)}/${g.max}</b><div class="qsub">${g.title.replace(/^[A-G] · /,'')}</div>`;h.appendChild(d)})}
function renderRewards(){const h=document.getElementById('rewardGrid');h.innerHTML='';rewards.forEach((r,i)=>{const k='reward'+i,b=document.createElement('button');b.className='reward '+(data.rewards[k]?'earned':'');b.innerHTML=`<span class="emoji">${r[0]}</span><b>${r[1]}</b>`;b.onclick=()=>{data.rewards[k]=!data.rewards[k];persist();renderRewards()};h.appendChild(b)})}
let currentGame=null,gameIndex=0,gameCorrect=0;
function startGame(name){currentGame=name;gameIndex=0;gameCorrect=0;document.getElementById('activityMenu').style.display='none';const area=document.getElementById('gameArea');area.classList.add('active');renderGame()}
function renderGame(){const area=document.getElementById('gameArea'),arr=games[currentGame];if(gameIndex>=arr.length){data.gameStars+=gameCorrect;persist();area.innerHTML=`<div class="prompt">🎉 Adventure complete!</div><p style="text-align:center;font-weight:850">You found ${gameCorrect} of ${arr.length} magic stars.</p><div class="row" style="justify-content:center"><button class="btn primary" onclick="closeGame()">Back to games</button></div>`;return}const q=arr[gameIndex];area.innerHTML=`<div class="game-head"><span class="badge kid">Question ${gameIndex+1} of ${arr.length}</span><button class="btn sm" onclick="closeGame()">Close</button></div><div class="prompt">${q.prompt}</div><div class="choices">${q.choices.map(c=>`<button class="choice" onclick="choose(this,'${c.replace(/'/g,"\\'")}')">${c}</button>`).join('')}</div><div class="game-feedback" id="feedback"></div>`}
function choose(btn,val){const q=games[currentGame][gameIndex],all=[...document.querySelectorAll('.choice')];all.forEach(b=>b.disabled=true);if(val===q.answer){btn.classList.add('correct');document.getElementById('feedback').textContent='✨ Yes! Magic star!';gameCorrect++}else{btn.classList.add('wrong');const right=all.find(b=>b.textContent===q.answer);if(right)right.classList.add('correct');document.getElementById('feedback').textContent='🌈 Nice try. Listen to the first sound again.'}setTimeout(()=>{gameIndex++;renderGame()},850)}
function closeGame(){document.getElementById('activityMenu').style.display='grid';const a=document.getElementById('gameArea');a.classList.remove('active');a.innerHTML=''}
function renderNextFocus(){const el=document.getElementById('nextFocus');const st=stage();const obs=data.observe.blend||'Not rated';let msg=st[1];if(obs==='Needs more practice')msg='Day 1 suggests blending is the bottleneck. Repeat blending with a DIFFERENT game: two-sound words first, continuous sounds, toy movement, then return to 3-sound CVC words.';else if(obs==='Developing')msg='Keep the same sound set, but give another playful blending/segmenting session before adding many new patterns.';else if(obs==='Mastered'&&groupScore('cvc')>=3)msg='She appears ready to accelerate: strengthen CVC spelling, contrast short vowels, and move toward short decodable sentences.';el.textContent=msg}
function updateStats(){document.getElementById('baseStat').textContent=total()+'/33';document.getElementById('rewardStat').textContent=Object.values(data.rewards).filter(Boolean).length+data.gameStars;const done=lesson.filter((_,i)=>data.steps['step'+i]).length;document.getElementById('lessonStat').textContent=Math.round(done/lesson.length*100)+'%';document.getElementById('stageStat').textContent=stage()[0];updateScore();renderNextFocus()}
document.querySelectorAll('.observe').forEach(s=>{s.value=data.observe[s.dataset.key]||'Not rated';s.addEventListener('change',()=>{data.observe[s.dataset.key]=s.value;persist();renderNextFocus()})});const notes=document.getElementById('notes');notes.value=data.notes;notes.addEventListener('input',()=>{data.notes=notes.value;persist(false)});notes.addEventListener('change',toast);
setTheme(data.theme);renderAssessment();renderLesson();renderTracker();renderRewards();renderBreakdown();updateStats();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
