const STORAGE_KEY='rainbowMagicLearningV2';
const STATUSES=['Not Introduced','Introduced','Learning','Developing','Mostly Mastered','Mastered','Review Needed'];
const themes={
  unicorn:{art:'🦄',title:'Rainbow Unicorn Kingdom'},ice:{art:'❄️',title:'Ice Princess Castle'},mermaid:{art:'🧜‍♀️',title:'Mermaid Ocean Adventure'},library:{art:'📚',title:'Enchanted Library'},tower:{art:'🏰',title:'Tower Princess Adventure'},fairy:{art:'🧚',title:'Fairy Garden'},dragon:{art:'🐉',title:'Dragon Rescue'},space:{art:'🚀',title:'Space Princess'}
};
const domains=[
{id:'reading',icon:'📖',title:'Phonics & Reading',priority:'Core',desc:'Sound awareness, systematic phonics, decoding, spelling, fluency, comprehension.',skills:['Letter sounds','Short vowels','Beginning sounds','Ending sounds','Medial sounds','Oral blending','Phoneme segmentation','CVC decoding','CVC encoding','Digraphs','Blends','Heart words','Sentence reading','Reading fluency','Comprehension']},
{id:'math',icon:'🔢',title:'Mathematics',priority:'Core',desc:'Quantity, number composition, operations with objects, patterns, spatial reasoning, measurement.',skills:['One-to-one correspondence','Quantity comparison','Number composition','Number bonds','Addition with objects','Subtraction with objects','Patterns','Sorting & classification','Shapes & spatial reasoning','Measurement & comparison','Sequencing','Early time concepts','Place-value foundations','Mathematical reasoning']},
{id:'language',icon:'💬',title:'Language & Comprehension',priority:'Core+',desc:'Vocabulary, complete sentences, listening, retelling, explaining, predicting and inference.',skills:['Vocabulary','Complete sentences','Listening comprehension','Story sequencing','Retelling','Describing','Comparing','Categorizing','Predicting','Explaining reasoning','WH questions','Simple inference']},
{id:'writing',icon:'✏️',title:'Writing & Handwriting',desc:'Pencil control, correct formation and meaningful early writing without excessive copying.',skills:['Pencil control','Letter formation','Number formation','Name writing','Phonetic spelling','Picture labeling','Sentence stems']},
{id:'logic',icon:'🧠',title:'Logic & Problem Solving',desc:'Patterns, sequencing, odd-one-out, deduction, cause/effect and coding-style thinking.',skills:['Pattern recognition','Sequencing','Odd one out','Categorization','Visual-spatial reasoning','Cause and effect','Simple deduction','Coding-style sequencing']},
{id:'science',icon:'🔬',title:'Science & Curiosity',desc:'Observe, predict, test, notice and explain using everyday phenomena.',skills:['Observation','Prediction','Testing ideas','Animals & habitats','Plants','Weather & seasons','Water','Light & sound','Magnets','Floating & sinking','Day & night','Space concepts']},
{id:'memory',icon:'🧩',title:'Memory & Attention',desc:'Listening memory, visual memory, following directions and working-memory growth.',skills:['Listening memory','Visual memory','2-step directions','3-step directions','Working memory','Attention control','Recall']},
{id:'sel',icon:'💛',title:'Social-Emotional Learning',desc:'Feelings, empathy, patience, frustration recovery, confidence, kindness and independence.',skills:['Emotion identification','Expressing feelings','Empathy','Patience & turn taking','Recovering from frustration','Asking for help','Kind choices','Confidence']},
{id:'executive',icon:'🧭',title:'Executive Function',desc:'Planning, persistence, impulse control, flexible thinking, completion and checking work.',skills:['Planning','Persistence','Impulse control','Flexible thinking','Task completion','Organization','Rule switching','Checking work']},
{id:'life',icon:'🏡',title:'Practical Life Skills',desc:'Age-appropriate independence, hygiene, safety awareness, organization and responsibility.',skills:['Cleaning up','Organizing belongings','Opening containers','Simple snack prep','Table manners','Hygiene','Safety awareness','Trusted-adult help','Simple responsibility']},
{id:'creativity',icon:'🎨',title:'Creativity & Imagination',desc:'Purposeful drawing, storytelling, building and flexible idea generation.',skills:['Story creation','Drawing to communicate','Pretend play','Creative building','Multiple solutions']},
{id:'fine',icon:'🤏',title:'Fine Motor Skills',desc:'Hand strength and control through meaningful manipulation and construction.',skills:['Pincer control','Cutting','Tearing & pasting','Manipulating small objects','Play-Doh control']},
{id:'gross',icon:'🏃‍♀️',title:'Gross Motor Development',desc:'Balance, coordination and body movement woven into learning missions.',skills:['Balance','Cross-body movement','Jumping & hopping','Movement sequences','Coordination']},
{id:'knowledge',icon:'🌍',title:'General Knowledge',desc:'Build useful background knowledge about the world through conversation and observation.',skills:['Community knowledge','Animals & places','Weather & seasons','Body knowledge','Earth & space','Everyday tools']}
];
const groups=[
{id:'consonants',title:'A · Consonant sounds',max:10,help:'Show one letter at a time. Ask: “What sound does this letter make?”',items:[['m','/mmmm/'],['s','/ssss/'],['t','short /t/'],['p','short /p/'],['n','/nnnn/'],['c','/k/'],['f','/ffff/'],['r','/r/'],['l','/llll/'],['h','/h/']]},
{id:'vowels',title:'B · Short vowels',max:5,help:'Ask for the short sound, not the letter name.',items:[['a','/ă/ apple'],['i','/ĭ/ igloo'],['o','/ŏ/ octopus'],['e','/ĕ/ egg'],['u','/ŭ/ umbrella']]},
{id:'begin',title:'C · Beginning sounds',max:3,help:'No letters. Ask for the first sound.',items:[['moon','/m/'],['sun','/s/'],['fish','/f/']]},
{id:'end',title:'D · Ending sounds',max:3,help:'Ask for the final sound.',items:[['cat','/t/'],['map','/p/'],['sun','/n/']]},
{id:'blend',title:'E · Oral blending',max:4,help:'Parent says sounds slowly. Child says the whole word.',items:[['/m/ /e/','me'],['/s/ /u/ /n/','sun'],['/m/ /a/ /p/','map'],['/f/ /i/ /sh/','fish']]},
{id:'segment',title:'F · Oral segmenting',max:4,help:'Parent says the word. Child says each sound.',items:[['me','/m/ /ē/'],['map','/m/ /a/ /p/'],['sun','/s/ /u/ /n/'],['cat','/c/ /a/ /t/']]},
{id:'cvc',title:'G · CVC decoding',max:4,help:'Only if blending is going reasonably well. No picture clues.',items:[['mat','decode'],['sit','decode'],['map','decode'],['cat','decode']]}
];
const lesson=[
['Magical introduction','1 min','Invite her into the adventure.','“Five magical sounds fell from Luna’s rainbow bag. Can you help find them?”'],
['Sound warm-up','2–3 min','No letters. Find words that start the same.','“Which two start the same: moon, mouse, sun?” Then sun/sock/map and pig/pan/tiger.'],
['Teach / review','3–4 min','Model m, s, t, p, a with pure sounds.','m=/mmmm/ · s=/ssss/ · t=short /t/ · p=short /p/ · a=/ă/'],
['Sound treasure hunt','4 min','Hunt household objects by first sound.','“Find something beginning with /ssss/.” Then /mmmm/, /p/, /t/.'],
['Jump to the sound','3 min','Place m,s,t,p cards on the floor.','“Jump to the beginning sound of moon.” Then sun, pig, top.'],
['Robot blending','3 min','Begin blending orally before letters.','Try /ă/ /t/ → at; /ă/ /m/ → am; /m/ /a/ /t/ → mat; /s/ /a/ /t/ → sat.'],
['Word building','2–3 min','Only if oral blending is going reasonably well.','Build m-a-t. Slide under each letter and blend. Change m to s for sat.'],
['Feed the Unicorn','1–2 min','Sort words by first sound.','For /m/: moon, sun, map. For /s/: sock, pig, sun.'],
['Quick review','1 min','Five short prompts without over-helping.','m sound · s sound · first sound in map · first sound in sun · blend /m/ /a/ /t/.'],
['Celebration','1 min','Praise effort and strategy.','“You used careful Sound Detective ears!”'],
['If she struggles','as needed','Simplify to two sounds and use blocks or toy movement.','Try /m/ /e/ → me or /ă/ /t/ → at. Stop positively if frustration grows.'],
['If it is very easy','1–3 min','Increase thinking rather than dumping in more letters.','Segment mat and sat using one block per phoneme.']
];
const activities=[
{id:'read-first',domain:'reading',skill:'Beginning sounds',icon:'🔎',title:'Magic First-Sound Hunt',minutes:4,type:'choice',objective:'Identify the first phoneme in a spoken word.',reason:'Beginning-sound isolation is an early phonemic-awareness foundation for decoding and spelling.',prompt:'Which word starts with /m/?',choices:['moon 🌙','sun ☀️','fish 🐟'],answer:'moon 🌙',success:'Gets 4 of 5 beginning sounds with little or no cueing.',materials:'No materials.',parent:'Say the target SOUND, not the letter name. Give about 3 seconds before helping.',extension:'Ask her to find one /m/ object in the room.'},
{id:'read-blend',domain:'reading',skill:'Oral blending',icon:'🌈',title:'Rainbow Blend Bridge',minutes:4,type:'choice',objective:'Blend three spoken phonemes into a whole word.',reason:'Oral blending builds the sound-combining process used later for written decoding.',prompt:'Parent says: /m/ /a/ /t/. Tap the whole word.',choices:['mat','sat','map'],answer:'mat',success:'Blends 3 of 4 two- or three-phoneme examples with little prompting.',materials:'No materials.',parent:'If needed, stretch continuous sounds and shorten the gaps: mmmm-aaaa-t.',extension:'Try /s/ /a/ /t/ without showing choices.'},
{id:'read-seg',domain:'reading',skill:'Phoneme segmentation',icon:'👏',title:'Princess Sound Steps',minutes:4,type:'coach',objective:'Break a spoken CVC word into individual phonemes.',reason:'Segmentation supports spelling because the child must hear every sound in sequence.',prompt:'Say “sun.” Ask her to move one block or tap one finger for every tiny sound.',success:'Segments 3 of 4 CVC words accurately with little prompting.',materials:'3 blocks, counters, or fingers.',parent:'Say: “Let’s break SUN into its tiny sounds.” Wait before modeling.',extension:'Try “map” and have her choose letter tiles after segmenting.'},
{id:'read-cvc',domain:'reading',skill:'CVC decoding',icon:'📖',title:'Castle Word Gate',minutes:5,type:'choice',objective:'Decode a CVC word using each grapheme rather than guessing.',reason:'This connects known sounds to actual reading.',prompt:'Touch each sound and read: m a p',choices:['map','mat','nap'],answer:'map',success:'Decodes about 4 of 5 taught-pattern CVC words without picture guessing.',materials:'Optional paper letter cards.',parent:'If she guesses, say: “Point to every sound.” Do not give a picture clue.',extension:'Build the same word from movable letters.'},
{id:'math-qty',domain:'math',skill:'Quantity comparison',icon:'⚖️',title:'Royal More-or-Less Picnic',minutes:4,type:'choice',objective:'Compare two visible quantities and identify more, less, or equal.',reason:'Quantity comparison develops number sense beyond reciting number names.',prompt:'Which group has MORE?  ●●●●   or   ●●',choices:['4 dots','2 dots','same'],answer:'4 dots',success:'Correctly compares 4 of 5 small quantities and can explain “because there are more.”',materials:'Optional buttons or fruit pieces.',parent:'After the answer ask: “How did you figure that out?”',extension:'Make two groups of 5 and 5 and ask about equal.'},
{id:'math-compose',domain:'math',skill:'Number composition',icon:'👑',title:'Make the Crown Number',minutes:5,type:'coach',objective:'Compose a target number from two smaller groups.',reason:'Understanding that a number can be made from parts supports later addition and subtraction.',prompt:'Make 5 using two groups. Example: 2 gems and 3 gems.',success:'Finds at least 3 different ways to make 5 using objects.',materials:'5–8 counters, blocks, buttons, or snacks.',parent:'Ask: “Can you make 5 a different way?” Avoid telling all combinations.',extension:'Try making 6.'},
{id:'math-add',domain:'math',skill:'Addition with objects',icon:'➕',title:'Unicorn Gem Addition',minutes:5,type:'coach',objective:'Join two small groups and determine the total using objects.',reason:'Concrete joining builds meaning for addition before memorized facts.',prompt:'Give Luna 2 gems. Add 1 more. How many gems now?',success:'Solves 4 of 5 joining problems within 5 using objects and explains the action.',materials:'Buttons, blocks, coins, or small toys.',parent:'Ask her to physically join the groups before counting.',extension:'Ask, “How did you know?”'},
{id:'language-retell',domain:'language',skill:'Retelling',icon:'📚',title:'Three-Part Story Spell',minutes:5,type:'coach',objective:'Retell a short event in beginning-middle-end order.',reason:'Sequenced retelling supports comprehension, oral language, memory, and later writing.',prompt:'Tell a tiny 3-part story: “A fairy lost a key. She looked under a leaf. She found it beside a flower.” Ask her to retell it.',success:'Retells all 3 major events in sensible order with minimal prompting.',materials:'No materials.',parent:'If needed ask only: “What happened first? Then what? How did it end?”',extension:'Ask her to add one detail about the setting.'},
{id:'language-why',domain:'language',skill:'Explaining reasoning',icon:'💬',title:'Princess Explain-It',minutes:3,type:'coach',objective:'Answer a simple “why” question in a complete thought.',reason:'Explaining strengthens expressive language and makes thinking visible.',prompt:'“Why might someone wear boots when it is raining?”',success:'Gives a relevant reason using a complete phrase or sentence.',materials:'No materials.',parent:'Accept her own reasonable wording. Expand rather than replace it.',extension:'Ask for a second possible reason.'},
{id:'writing-label',domain:'writing',skill:'Picture labeling',icon:'✏️',title:'Label the Magic Picture',minutes:5,type:'coach',objective:'Use known sounds to write or build a meaningful label.',reason:'Meaningful encoding connects phonics to writing without excessive handwriting.',prompt:'Draw or choose a simple picture such as a sun. Help her stretch the word and write/build the sounds she can hear.',success:'Represents at least the first and final sounds independently; more if ready.',materials:'Paper + pencil or letter tiles.',parent:'Prioritize sound thinking over perfect handwriting.',extension:'Add a sentence stem: “I see a ___.”'},
{id:'logic-pattern',domain:'logic',skill:'Pattern recognition',icon:'🧠',title:'Dragon Pattern Path',minutes:4,type:'choice',objective:'Identify and extend a repeating visual pattern.',reason:'Pattern recognition supports prediction, mathematical structure, and reasoning.',prompt:'What comes next? 🔴 🔵 🔴 🔵 ?',choices:['🔴','🔵','🟢'],answer:'🔴',success:'Extends 4 of 5 AB/ABB patterns and can say the repeating rule.',materials:'Optional colored blocks.',parent:'Ask: “What part keeps repeating?”',extension:'Build an ABB pattern with objects.'},
{id:'logic-odd',domain:'logic',skill:'Odd one out',icon:'🕵️‍♀️',title:'Royal Odd-One-Out Mystery',minutes:4,type:'coach',objective:'Identify an item that does not belong and justify the category.',reason:'Categorization and justification strengthen flexible reasoning and vocabulary.',prompt:'Which one does not belong: apple, banana, carrot? Why?',success:'Chooses a reasonable odd item and gives a category-based explanation.',materials:'No materials.',parent:'More than one answer can be valid if the explanation makes sense.',extension:'Ask her to create her own odd-one-out set.'},
{id:'science-float',domain:'science',skill:'Prediction',icon:'🔬',title:'Mermaid Float-or-Sink Lab',minutes:6,type:'coach',objective:'Make a prediction, test it, observe the result, and compare prediction with evidence.',reason:'This practices the scientific cycle rather than memorizing a fact.',prompt:'Choose 3 safe objects. Before each goes in water ask: “Will it float or sink? Why do you think so?”',success:'Makes a prediction for each object and describes what actually happened.',materials:'Bowl of water + 3 safe waterproof objects; adult supervision.',parent:'The prediction does not need to be correct. Reward noticing and revising ideas.',extension:'Ask what object she would test next and why.'},
{id:'science-shadow',domain:'science',skill:'Observation',icon:'☀️',title:'Shadow Detective',minutes:5,type:'coach',objective:'Observe how blocking light creates a shadow.',reason:'Direct observation builds causal reasoning about light.',prompt:'Use a flashlight and a toy. Move the toy closer to and farther from the light. What changes?',success:'Describes at least one change she notices and connects the toy blocking light to the shadow.',materials:'Flashlight + toy.',parent:'Ask “What do you notice?” before explaining.',extension:'Predict what will happen before moving the toy.'},
{id:'memory-directions',domain:'memory',skill:'2-step directions',icon:'👂',title:'Fairy Two-Step Mission',minutes:3,type:'coach',objective:'Hold and execute a two-step spoken direction in working memory.',reason:'Following directions strengthens listening memory and executive control.',prompt:'Say once: “Touch the table, then bring me the blue crayon.”',success:'Completes 4 of 5 two-step directions without needing them repeated.',materials:'Everyday room objects.',parent:'Say the direction once at normal pace. Reduce to one step if repeated failure starts.',extension:'When consistently easy, try one 3-step direction.'},
{id:'executive-switch',domain:'executive',skill:'Rule switching',icon:'🧭',title:'Magic Rule Switch',minutes:4,type:'coach',objective:'Switch between two simple response rules.',reason:'Rule switching develops flexible thinking and inhibition.',prompt:'Rule 1: when parent says “sun,” clap; when parent says “moon,” touch your head. After 4 turns, switch the rules.',success:'Follows the new switched rule on 4 of 5 trials after a reminder.',materials:'No materials.',parent:'Go slowly when switching. One reminder is okay.',extension:'Add “star = jump” only if the two-rule game is easy.'},
{id:'sel-feelings',domain:'sel',skill:'Emotion identification',icon:'💛',title:'Princess Feelings Detective',minutes:4,type:'coach',objective:'Identify an emotion and connect it to a plausible situation.',reason:'Naming emotions supports communication and self-regulation.',prompt:'“A child built a tower and it fell down. What might she feel? What could help?”',success:'Names a plausible feeling and one safe/helpful response.',materials:'No materials.',parent:'Do not label the child as good/bad. Talk about feelings, behaviors, and choices.',extension:'Ask for another feeling someone might have in the same situation.'},
{id:'life-cleanup',domain:'life',skill:'Cleaning up',icon:'🏡',title:'Royal Reset Mission',minutes:4,type:'coach',objective:'Complete a short cleanup routine with increasing independence.',reason:'Practical routines build organization, responsibility, and task completion.',prompt:'Pick one small area. Mission: put toys in their homes, place books together, then check the floor.',success:'Completes the 2–3 step cleanup with no more than one reminder.',materials:'A small real cleanup area.',parent:'Keep the area small enough to finish successfully.',extension:'Ask her to decide the order next time.'},
{id:'creativity-story',domain:'creativity',skill:'Story creation',icon:'🎨',title:'Make a Magic Mini-Story',minutes:5,type:'coach',objective:'Create a simple story with character, problem, and solution.',reason:'Story generation integrates imagination with language organization and causal thinking.',prompt:'Choose a character: unicorn, mermaid, dragon, or princess. Ask: “What does the character want? What problem happens? How is it solved?”',success:'Creates a connected 3-part idea with support as needed.',materials:'Optional paper for drawing.',parent:'Follow her ideas. Ask structure questions rather than taking over the story.',extension:'Draw the ending and label one thing.'},
{id:'fine-sort',domain:'fine',skill:'Pincer control',icon:'🤏',title:'Tiny Gem Rescue',minutes:4,type:'coach',objective:'Use controlled finger movements to transfer and sort small safe objects.',reason:'Pincer strength and precision support later pencil and scissor control.',prompt:'Move 10 large buttons/pom-poms into two cups using thumb and pointer finger.',success:'Transfers items with controlled grasp and minimal dropping.',materials:'Large buttons/pom-poms + 2 cups. Avoid choking hazards.',parent:'Use objects appropriate for a 5-year-old and supervise.',extension:'Sort by color while transferring.'},
{id:'gross-sequence',domain:'gross',skill:'Movement sequences',icon:'🏃‍♀️',title:'Rainbow Movement Code',minutes:4,type:'coach',objective:'Remember and perform a short movement sequence.',reason:'Movement sequencing combines gross motor coordination with working memory.',prompt:'Do: clap → jump → touch knees. Ask her to copy the sequence.',success:'Repeats a 3-movement sequence correctly on 3 of 4 attempts.',materials:'Open safe floor space.',parent:'Reduce to two movements if needed.',extension:'Let her invent a sequence for the parent.'},
{id:'knowledge-community',domain:'knowledge',skill:'Community knowledge',icon:'🌍',title:'Who Helps Us?',minutes:4,type:'coach',objective:'Connect common community helpers with their roles.',reason:'Background knowledge supports vocabulary, comprehension, and practical safety understanding.',prompt:'Ask: “Who might help if there is a fire? What does a librarian help people do?”',success:'Explains the role of 3 familiar helpers in her own words.',materials:'Optional picture cards.',parent:'Keep examples concrete and local to daily life.',extension:'Talk about one trusted adult she could ask for help.'}
];
const rewards=[['🌈','Rainbow Star'],['💎','Unicorn Gem'],['🗝️','Princess Key'],['🔮','Magic Crystal'],['⭐','Courage Badge'],['📖','Reading Spark'],['👑','Math Crown'],['🔬','Science Star'],['🧠','Thinking Gem'],['💛','Kindness Heart'],['🧭','Focus Compass'],['✨','Independent Spark']];
let data=loadData();
let currentActivity=null;
function loadData(){
  const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');
  const legacy=JSON.parse(localStorage.getItem('magicPhonics')||'{}');
  const old=Object.keys(saved).length?saved:legacy;
  return {theme:old.theme||'unicorn',answers:old.answers||{},steps:old.steps||{},observe:old.observe||{},notes:old.notes||'',skills:old.skills||{},evidence:old.evidence||{},rewards:old.rewards||{},quest:old.quest||null,questDate:old.questDate||'',questResults:old.questResults||{},questHistory:old.questHistory||[]};
}
function persist(show=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));updateStats();if(show)toast()}
function toast(){const t=document.getElementById('toast');t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),850)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function esc(v){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='quest')ensureQuest();if(id==='parent'){renderSkillTracker();renderBreakdown();renderNextFocus()}if(id==='learn')renderDomains()}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function setTheme(t){data.theme=t;document.body.dataset.theme=t;document.getElementById('themeSelect').value=t;document.getElementById('heroArt').textContent=(themes[t]||themes.unicorn).art;persist(false)}
function skillKey(domain,skill){return `${domain}::${skill}`}
function getStatus(domain,skill){return data.skills[skillKey(domain,skill)]||'Not Introduced'}
function setStatus(domain,skill,status,manual=false){data.skills[skillKey(domain,skill)]=status;if(manual)persist()}
function recordEvidence(activity,score){
  const k=skillKey(activity.domain,activity.skill),arr=data.evidence[k]||[];
  arr.push({date:todayKey(),score,activityId:activity.id});
  data.evidence[k]=arr.slice(-12);
  data.skills[k]=deriveStatus(data.skills[k]||'Not Introduced',data.evidence[k]);
  persist(false);renderSkillTracker();
}
function deriveStatus(current,arr){
  if(!arr.length)return 'Not Introduced';
  const recent=arr.slice(-6),avg=recent.reduce((n,x)=>n+x.score,0)/recent.length;
  const dates=new Set(recent.map(x=>x.date)).size,formats=new Set(recent.map(x=>x.activityId)).size;
  if(current==='Mastered'&&recent.slice(-2).some(x=>x.score<.5))return 'Review Needed';
  if(recent.length>=5&&dates>=2&&avg>=.85&&formats>=2)return 'Mastered';
  if(recent.length>=4&&avg>=.8)return 'Mostly Mastered';
  if(recent.length>=3&&avg>=.7)return 'Developing';
  if(recent.length>=2&&avg>=.55)return 'Learning';
  return 'Introduced';
}
function domainById(id){return domains.find(d=>d.id===id)}
function activitiesFor(domain){return activities.filter(a=>a.domain===domain)}
function chooseActivity(domain,offset=0){
  const list=activitiesFor(domain);if(!list.length)return null;
  const review=list.find(a=>getStatus(a.domain,a.skill)==='Review Needed');if(review)return review;
  const unmastered=list.filter(a=>getStatus(a.domain,a.skill)!=='Mastered');
  const pool=unmastered.length?unmastered:list;
  const completed=Object.keys(data.evidence).reduce((n,k)=>n+(k.startsWith(domain+'::')?(data.evidence[k]||[]).length:0),0);
  return pool[(completed+offset)%pool.length];
}
function makeQuest(){
  const rotate=['language','logic','science','memory','sel','executive','life','knowledge'];
  const move=['writing','creativity','fine','gross'];
  const day=Math.floor(Date.now()/86400000);
  const ids=[chooseActivity('reading'),chooseActivity('math'),chooseActivity(rotate[day%rotate.length]),chooseActivity(move[day%move.length])].filter(Boolean).map(a=>a.id);
  data.quest=ids;data.questDate=todayKey();data.questResults={};persist(false);renderQuest();
}
function ensureQuest(){if(!data.quest||data.questDate!==todayKey())makeQuest();else renderQuest()}
function refreshQuest(){makeQuest();toast()}
function renderQuest(){
  document.getElementById('questDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
  document.getElementById('questTitle').textContent=(themes[data.theme]||themes.unicorn).title+' Quest';
  const h=document.getElementById('questCards');h.innerHTML='';
  (data.quest||[]).forEach((id,i)=>{const a=activities.find(x=>x.id===id);if(!a)return;const done=data.questResults[id]!=null,d=document.createElement('button');d.className='quest-card '+(done?'done':'');d.onclick=()=>runActivity(id);d.innerHTML=`<span class="quest-num">${done?'✓':i+1}</span><span class="quest-icon">${a.icon}</span><span class="quest-copy"><small>${domainById(a.domain).title} · ${a.minutes} min</small><b>${a.title}</b><em>${a.objective}</em></span><span class="quest-arrow">›</span>`;h.appendChild(d)});
  updateStats();
}
function runActivity(id){currentActivity=activities.find(x=>x.id===id);if(!currentActivity)return;const a=currentActivity,runner=document.getElementById('activityRunner');runner.classList.add('active');
  const choice=a.type==='choice'?`<div class="activity-prompt">${a.prompt}</div><div class="choices">${a.choices.map(c=>`<button class="choice" onclick="answerActivity(this,${JSON.stringify(c)})">${c}</button>`).join('')}</div><div id="activityFeedback" class="game-feedback"></div>`:`<div class="activity-prompt coach-prompt">${a.prompt}</div><div class="rating"><button onclick="rateActivity(1)">✨ Independent</button><button onclick="rateActivity(.6)">🤝 With help</button><button onclick="rateActivity(.2)">🌱 Not yet</button></div>`;
  runner.innerHTML=`<div class="runner-head"><div><span class="badge kid">${a.icon} ${domainById(a.domain).title}</span><h3>${a.title}</h3></div><button class="btn sm" onclick="closeActivity()">Close</button></div><div class="objective-box"><b>Learning objective</b><span>${a.objective}</span></div>${choice}<details class="coach-note"><summary>🧑 Parent coaching note</summary><p><b>Target skill:</b> ${a.skill}</p><p><b>Why this activity:</b> ${a.reason}</p><p><b>Materials:</b> ${a.materials}</p><p><b>What to do/say:</b> ${a.parent}</p><p><b>Success looks like:</b> ${a.success}</p><p><b>If easy:</b> ${a.extension}</p></details>`;
  runner.scrollIntoView({behavior:'smooth',block:'start'});
}
function answerActivity(btn,val){const a=currentActivity;if(!a)return;const buttons=[...document.querySelectorAll('#activityRunner .choice')];buttons.forEach(b=>b.disabled=true);const ok=val===a.answer;if(ok){btn.classList.add('correct');document.getElementById('activityFeedback').textContent='✨ Yes! Now tell your grown-up how you knew.';completeActivity(a,1)}else{btn.classList.add('wrong');const right=buttons.find(b=>b.textContent===a.answer);if(right)right.classList.add('correct');document.getElementById('activityFeedback').textContent='🌈 Nice try. Use the clue and try the thinking again.';completeActivity(a,.35)}}
function rateActivity(score){if(!currentActivity)return;completeActivity(currentActivity,score);document.getElementById('activityRunner').insertAdjacentHTML('beforeend','<div class="completion">✨ Mission recorded. Effort and strategy count too.</div>')}
function completeActivity(a,score){recordEvidence(a,score);data.questResults[a.id]=score;data.questHistory.push({date:todayKey(),activityId:a.id,score});data.questHistory=data.questHistory.slice(-80);persist(false);renderQuest();awardAuto(score,a)}
function awardAuto(score,a){if(score>=.9){const idx=a.domain==='math'?6:a.domain==='science'?7:a.domain==='reading'?5:score>=1?0:4;data.rewards['reward'+idx]=true;persist(false);renderRewards()}}
function closeActivity(){document.getElementById('activityRunner').classList.remove('active');document.getElementById('activityRunner').innerHTML='';currentActivity=null}
function renderDomains(){const h=document.getElementById('domainGrid');h.innerHTML='';domains.forEach(d=>{const mastered=d.skills.filter(s=>getStatus(d.id,s)==='Mastered').length,b=document.createElement('button');b.className='domain-card';b.onclick=()=>openDomain(d.id);b.innerHTML=`<span class="domain-icon">${d.icon}</span><span class="domain-copy"><small>${d.priority||'Rotating domain'}</small><b>${d.title}</b><em>${d.desc}</em><span class="domain-progress">${mastered}/${d.skills.length} mastered</span></span>`;h.appendChild(b)})}
function openDomain(id){go('learn');const d=domainById(id),h=document.getElementById('domainDetail');if(!d)return;const acts=activitiesFor(id);h.innerHTML=`<div class="section-title"><h2>${d.icon} ${d.title}</h2><p>${d.desc}</p></div><div class="card"><h3>Skill progression</h3><div class="skill-chip-wrap">${d.skills.map(s=>`<span class="skill-chip ${slug(getStatus(d.id,s))}">${esc(s)}<small>${getStatus(d.id,s)}</small></span>`).join('')}</div></div><div class="section-title"><h2>Purposeful activities</h2><p>Every activity shows objective, reason and success criterion.</p></div><div class="activity-grid">${acts.map(a=>`<button class="activity" onclick="runLearningActivity('${a.id}')"><span class="big">${a.icon}</span><b>${a.title}</b><p>${a.objective}</p><small>${a.minutes} min · ${a.skill}</small></button>`).join('')||'<div class="card">Activities for this domain will rotate through daily quests.</div>'}</div><div id="learnRunner" class="card runner"></div>`;h.scrollIntoView({behavior:'smooth'});
}
function runLearningActivity(id){const target=document.getElementById('learnRunner');currentActivity=activities.find(x=>x.id===id);if(!currentActivity||!target)return;const a=currentActivity;target.classList.add('active');const choice=a.type==='choice'?`<div class="activity-prompt">${a.prompt}</div><div class="choices">${a.choices.map(c=>`<button class="choice" onclick="answerLearnActivity(this,${JSON.stringify(c)})">${c}</button>`).join('')}</div><div id="learnFeedback" class="game-feedback"></div>`:`<div class="activity-prompt coach-prompt">${a.prompt}</div><div class="rating"><button onclick="rateLearnActivity(1)">✨ Independent</button><button onclick="rateLearnActivity(.6)">🤝 With help</button><button onclick="rateLearnActivity(.2)">🌱 Not yet</button></div>`;target.innerHTML=`<div class="runner-head"><div><span class="badge kid">${a.icon} ${a.skill}</span><h3>${a.title}</h3></div><button class="btn sm" onclick="this.closest('.runner').classList.remove('active')">Close</button></div><div class="objective-box"><b>Objective</b><span>${a.objective}</span></div>${choice}<details class="coach-note" open><summary>🧑 Parent coaching note</summary><p><b>Why:</b> ${a.reason}</p><p><b>Materials:</b> ${a.materials}</p><p><b>Coach:</b> ${a.parent}</p><p><b>Success:</b> ${a.success}</p><p><b>Extension:</b> ${a.extension}</p></details>`;target.scrollIntoView({behavior:'smooth'})}
function answerLearnActivity(btn,val){const a=currentActivity,buttons=[...document.querySelectorAll('#learnRunner .choice')];buttons.forEach(b=>b.disabled=true);const ok=val===a.answer;btn.classList.add(ok?'correct':'wrong');if(!ok){const right=buttons.find(b=>b.textContent===a.answer);if(right)right.classList.add('correct')}document.getElementById('learnFeedback').textContent=ok?'✨ Yes! Explain how you knew.':'🌈 Use the clue and think again.';recordEvidence(a,ok?1:.35)}
function rateLearnActivity(score){recordEvidence(currentActivity,score);document.getElementById('learnRunner').insertAdjacentHTML('beforeend','<div class="completion">✨ Practice recorded.</div>')}
function slug(s){return s.toLowerCase().replace(/[^a-z]+/g,'-')}
function renderAssessment(){const h=document.getElementById('assessment');h.innerHTML='';groups.forEach(g=>{const c=document.createElement('div');c.className='card';c.style.marginTop='12px';let s=`<div class="kicker">${g.title}</div><h3>${g.help}</h3>`;g.items.forEach((it,i)=>{const k=`${g.id}-${i}`,v=data.answers[k];s+=`<div class="question"><div><div class="qtext">${esc(it[0])}</div><div class="qsub">Expected: ${esc(it[1])}</div></div><div class="score-buttons"><button class="yes ${v===1?'active':''}" onclick="answerBaseline('${k}',1)">✓</button><button class="no ${v===0?'active':''}" onclick="answerBaseline('${k}',0)">×</button></div></div>`});c.innerHTML=s;h.appendChild(c)});updateBaselineScore()}
function answerBaseline(k,v){data.answers[k]=v;syncBaselineSkills();persist(false);renderAssessment();renderBreakdown();renderNextFocus()}
function groupScore(id){const g=groups.find(x=>x.id===id);return g.items.reduce((n,_,i)=>n+(data.answers[`${id}-${i}`]===1?1:0),0)}
function baselineTotal(){return groups.reduce((n,g)=>n+groupScore(g.id),0)}
function readingStage(){const c=groupScore('consonants'),v=groupScore('vowels'),b=groupScore('blend'),s=groupScore('segment'),r=groupScore('cvc');if(r>=3&&b>=3&&s>=3)return['CVC+','CVC decoding looks strong in this snapshot. Build repeated evidence through CVC spelling, short-vowel contrast, fluency, and early sentences.'];if(c>=7&&v>=3&&b>=3&&s>=3)return['CVC','Oral sound skills look ready to connect to written CVC reading and spelling.'];if(c>=7)return['Blend','Letter sounds look mostly secure; focus on oral blending and segmenting before pushing more written words.'];return['Foundation','Strengthen automatic consonant and short-vowel sounds, then connect them to beginning sounds.']}
function syncBaselineSkills(){const map=[['consonants','Letter sounds',10],['vowels','Short vowels',5],['begin','Beginning sounds',3],['end','Ending sounds',3],['blend','Oral blending',4],['segment','Phoneme segmentation',4],['cvc','CVC decoding',4]];map.forEach(([gid,skill,max])=>{const answered=groups.find(g=>g.id===gid).items.filter((_,i)=>data.answers[`${gid}-${i}`]!=null).length;if(!answered)return;const ratio=groupScore(gid)/max;const k=skillKey('reading',skill);if(ratio>=.8&&getStatus('reading',skill)==='Not Introduced')data.skills[k]='Mostly Mastered';else if(ratio>=.55&&['Not Introduced','Introduced'].includes(getStatus('reading',skill)))data.skills[k]='Developing';else if(ratio<.55)data.skills[k]='Learning'})}
function updateBaselineScore(){const n=baselineTotal();document.getElementById('scoreNow').textContent=n;document.getElementById('scoreBar').style.width=(n/33*100)+'%';document.getElementById('recommendation').textContent=readingStage()[1]}
function resetBaseline(){if(confirm('Clear the reading baseline answers?')){data.answers={};persist();renderAssessment();renderBreakdown();renderNextFocus()}}
function renderLesson(){const h=document.getElementById('lessonSteps');h.innerHTML='';lesson.forEach((x,i)=>{const k='step'+i,d=document.createElement('div');d.className='card step';d.innerHTML=`<div class="step-num">${i+1}</div><div><div class="kicker">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p><div class="say">${x[3]}</div><label class="checkline"><input type="checkbox" ${data.steps[k]?'checked':''} onchange="toggleStep('${k}',this.checked)"><span><b>Done</b> — completed or intentionally skipped.</span></label></div>`;h.appendChild(d)})}
function toggleStep(k,v){data.steps[k]=v;persist()}
function renderSkillTracker(){const h=document.getElementById('skillTracker');h.innerHTML='';domains.forEach(d=>{const details=document.createElement('details');details.className='domain-tracker';details.innerHTML=`<summary>${d.icon} <b>${d.title}</b><span>${d.skills.filter(s=>getStatus(d.id,s)==='Mastered').length}/${d.skills.length} mastered</span></summary><div class="tracker-body">${d.skills.map(s=>{const v=getStatus(d.id,s);return `<div class="tracker-row"><span>${esc(s)}</span><select class="status-select" onchange="manualSkill('${d.id}',${JSON.stringify(s)},this.value)">${STATUSES.map(st=>`<option ${st===v?'selected':''}>${st}</option>`).join('')}</select></div>`}).join('')}</div>`;h.appendChild(details)})}
function manualSkill(domain,skill,status){setStatus(domain,skill,status);persist()}
function renderBreakdown(){const h=document.getElementById('breakdown');h.innerHTML='';groups.forEach(g=>{const d=document.createElement('div');d.className='mini';d.innerHTML=`<b>${groupScore(g.id)}/${g.max}</b><div class="qsub">${g.title.replace(/^[A-G] · /,'')}</div>`;h.appendChild(d)})}
function renderRewards(){const h=document.getElementById('rewardGrid');h.innerHTML='';rewards.forEach((r,i)=>{const k='reward'+i,b=document.createElement('button');b.className='reward '+(data.rewards[k]?'earned':'');b.innerHTML=`<span class="emoji">${r[0]}</span><b>${r[1]}</b>`;b.onclick=()=>{data.rewards[k]=!data.rewards[k];persist();renderRewards()};h.appendChild(b)})}
function renderNextFocus(){const el=document.getElementById('nextFocus');if(!el)return;const st=readingStage(),due=findReviewNeeded();let msg=st[1];if(data.observe.blend==='Needs more practice')msg='Blending appears to be the current bottleneck. Keep the same small sound set and use a different oral blending game before adding many new patterns.';else if(due.length)msg=`Spaced review is due for ${due.slice(0,3).map(x=>x.skill).join(', ')}. Mix one of these into the next quest while keeping literacy and math central.`;el.textContent=msg}
function findReviewNeeded(){const out=[];Object.entries(data.skills).forEach(([k,status])=>{if(status==='Review Needed'){const [domain,skill]=k.split('::');out.push({domain,skill})}});return out}
function updateStats(){const mastered=Object.values(data.skills).filter(s=>s==='Mastered').length,done=(data.quest||[]).filter(id=>data.questResults[id]!=null).length;document.getElementById('baseStat').textContent=baselineTotal()+'/33';document.getElementById('masteredStat').textContent=mastered;document.getElementById('questStat').textContent=`${done}/${(data.quest||[]).length||4}`;document.getElementById('rewardStat').textContent=Object.values(data.rewards).filter(Boolean).length;updateBaselineScore();renderNextFocus()}
document.querySelectorAll('.observe').forEach(s=>{s.value=data.observe[s.dataset.key]||'Not rated';s.addEventListener('change',()=>{data.observe[s.dataset.key]=s.value;persist();renderNextFocus()})});
const notes=document.getElementById('notes');notes.value=data.notes;notes.addEventListener('input',()=>{data.notes=notes.value;persist(false)});notes.addEventListener('change',toast);
setTheme(data.theme);renderAssessment();renderLesson();renderDomains();renderSkillTracker();renderRewards();renderBreakdown();ensureQuest();updateStats();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
