const ALLOWED_INTERACTIONS=new Set(['tap_choice','multi_select','drag_drop','sort','match','memory','sequence','word_builder','number_manipulative','pattern_builder','find_it','trace','story_choice','movement','offline_activity']);

const structuredActivities=[
{
 id:'read-first',domain:'reading',skill:'Beginning sounds',icon:'🦄',title:'Luna’s Sound Clouds',character:'Luna',character_icon:'🦄',objective:'Sort pictures by beginning phoneme.',reason:'Sorting forces the child to listen to the first sound and classify by phoneme.',interaction_type:'sort',instruction_text:'Sort the sound pictures!',spoken_instruction:'Put the pictures that start with mmm in Luna’s pink cloud and the pictures that start with sss in the blue cloud.',character_prompt:'Help me sort my clouds!',items:[{id:'moon',label:'Moon',emoji:'🌙'},{id:'map',label:'Map',emoji:'🗺️'},{id:'sun',label:'Sun',emoji:'☀️'},{id:'sock',label:'Sock',emoji:'🧦'}],targets:[{id:'m',label:'/m/ cloud',emoji:'☁️'},{id:'s',label:'/s/ cloud',emoji:'☁️'}],correct_answer:{moon:'m',map:'m',sun:'s',sock:'s'},distractors:[],hint_1:'Listen to the first sound.',hint_2:'Mmmmoon starts with /m/.',hint_3:'Moon and map go to /m/.',success_feedback:'Yes! Moon and map start with /m/.',retry_feedback:'Almost! Listen to the first sound again.',mastery_signal:'Correctly sorts beginning /m/ and /s/ pictures without guessing.',difficulty:1,estimated_minutes:4,reward:'✨ Shiny Sound Star',materials:'No materials.',parent:'Use pure /mmmm/ and /ssss/ sounds.',extension:'Find one /m/ object in the room.'
},
{
 id:'read-blend',domain:'reading',skill:'Oral blending',icon:'🌈',title:'Rainbow Blend Bridge',character:'Luna',character_icon:'🦄',objective:'Blend three spoken phonemes into a word.',reason:'Oral blending is the sound-combining process used during decoding.',interaction_type:'tap_choice',instruction_text:'Push the sounds together!',spoken_instruction:'Listen: mmm, aaa, t. Tap the word those sounds make.',character_prompt:'Build my rainbow bridge!',items:[{id:'mat',label:'mat'},{id:'sat',label:'sat'},{id:'map',label:'map'}],targets:[],correct_answer:'mat',distractors:['sat','map'],hint_1:'Hear the sounds again: mmm, aaa, t.',hint_2:'The word starts with mmm and ends with t.',hint_3:'Slide them together: mmm-aa-t, mat.',success_feedback:'You blended every sound: /m/ /a/ /t/ makes mat.',retry_feedback:'Almost! Touch each sound in your mind and blend again.',mastery_signal:'Blends /m/ /a/ /t/ with little or no prompting.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Blend Star',materials:'No materials.',parent:'If needed, shorten the pauses between sounds.',extension:'Blend /s/ /a/ /t/ without choices.'
},
{
 id:'read-cvc',domain:'reading',skill:'CVC decoding',icon:'👑',title:'Princess Word Gate',character:'Book Princess',character_icon:'👸',objective:'Build and decode the CVC word map.',reason:'Building the word requires attending to each phoneme-grapheme correspondence.',interaction_type:'word_builder',instruction_text:'Build the word MAP!',spoken_instruction:'Drag the letters to build map. Listen: mmm, aaa, p.',character_prompt:'Unlock my library word!',items:[{id:'m1',label:'m',value:'m'},{id:'a1',label:'a',value:'a'},{id:'p1',label:'p',value:'p'},{id:'s1',label:'s',value:'s'},{id:'t1',label:'t',value:'t'}],targets:[{id:'slot1',label:'1'},{id:'slot2',label:'2'},{id:'slot3',label:'3'}],correct_answer:['m','a','p'],distractors:['s','t'],hint_1:'Say the tiny sounds: /m/ /a/ /p/.',hint_2:'The first letter is m.',hint_3:'Use m, then a, then p.',success_feedback:'You built MAP from all three sounds.',retry_feedback:'Listen again and fill each sound slot.',mastery_signal:'Selects m-a-p in order and blends the completed word.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Reading Star',materials:'Optional letter tiles.',parent:'Do not encourage picture guessing.',extension:'Build sat next.'
},
{
 id:'read-seg',domain:'reading',skill:'Phoneme segmentation',icon:'⭐',title:'Shiny Sound Steps',character:'Luna',character_icon:'🦄',objective:'Represent each phoneme in sun in sequence.',reason:'Moving one star per sound makes phoneme segmentation visible.',interaction_type:'sequence',instruction_text:'Put SUN sounds in order!',spoken_instruction:'Break sun into its tiny sounds and put the sound cards in order.',character_prompt:'Step across three sound stars!',items:[{id:'s',label:'/s/'},{id:'u',label:'/u/'},{id:'n',label:'/n/'}],targets:[{id:'first',label:'FIRST'},{id:'next',label:'NEXT'},{id:'last',label:'LAST'}],correct_answer:['s','u','n'],distractors:[],hint_1:'Say sun slowly.',hint_2:'Listen: sss-un.',hint_3:'Start with /s/, then /u/, then /n/.',success_feedback:'You heard all three sounds in SUN.',retry_feedback:'Almost! Stretch SUN and listen for each tiny sound.',mastery_signal:'Orders /s/ /u/ /n/ independently.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Sound Star',materials:'No materials.',parent:'Let her use finger taps while saying the sounds.',extension:'Segment map.'
},
{
 id:'math-compose',domain:'math',skill:'Number composition',icon:'🧜‍♀️',title:'Mermaid Pearl Chest',character:'Mermaid Princess',character_icon:'🧜‍♀️',objective:'Complete a set of five from a known part.',reason:'Adding manipulatives makes part-whole number composition concrete.',interaction_type:'number_manipulative',instruction_text:'Give her exactly 5 pearls!',spoken_instruction:'The mermaid needs five pearls. She already has three. Add enough pearls to make five.',character_prompt:'My pearl chest needs five!',items:[{id:'p1',label:'Pearl',emoji:'⚪'},{id:'p2',label:'Pearl',emoji:'⚪'},{id:'p3',label:'Pearl',emoji:'⚪'},{id:'p4',label:'Pearl',emoji:'⚪'}],targets:[{id:'chest',label:'Treasure Chest',emoji:'🧰'}],correct_answer:2,distractors:[1,3,4],hint_1:'Count the three pearls first.',hint_2:'After four comes five.',hint_3:'Add two pearls: 3 and 2 make 5.',success_feedback:'You added 2. Three plus two makes five.',retry_feedback:'Count what is already there, then add only what is missing.',mastery_signal:'Adds exactly two objects to complete a total of five.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Math Star',materials:'Optional real counters.',parent:'Ask how many were added after she finishes.',extension:'Start with 2 and make 5.' ,initial_count:3,target_total:5
},
{
 id:'math-qty',domain:'math',skill:'Quantity comparison',icon:'❄️',title:'Ice Princess Snowflake Sort',character:'Ice Princess',character_icon:'👸❄️',objective:'Identify which set has more objects.',reason:'Comparing visible sets develops quantity sense, not rote numeral naming.',interaction_type:'tap_choice',instruction_text:'Which side has MORE?',spoken_instruction:'Look at both snowflake groups. Tap the group that has more.',character_prompt:'Which snow pile is bigger?',items:[{id:'four',label:'❄️ ❄️ ❄️ ❄️'},{id:'two',label:'❄️ ❄️'},{id:'same',label:'Same'}],targets:[],correct_answer:'four',distractors:['two','same'],hint_1:'Count each group slowly.',hint_2:'One group has four. One has two.',hint_3:'Four is more than two.',success_feedback:'Right. Four snowflakes are more than two.',retry_feedback:'Count both groups, then compare them.',mastery_signal:'Chooses the larger quantity without relying on answer position.',difficulty:1,estimated_minutes:3,reward:'✨ Shiny Math Star',materials:'No materials.',parent:'Ask “How did you know?” after the tap.',extension:'Compare equal groups.'
},
{
 id:'math-pattern',domain:'math',skill:'Patterns',icon:'❄️',title:'Frozen Bridge Pattern',character:'Ice Princess',character_icon:'👸❄️',objective:'Extend an AB repeating pattern.',reason:'Constructing the missing unit reveals understanding of the repeating rule.',interaction_type:'pattern_builder',instruction_text:'Finish the frozen pattern!',spoken_instruction:'Look at the pattern: star, heart, star, heart. Choose what comes next.',character_prompt:'Fix my frozen bridge!',items:[{id:'star',label:'⭐',value:'⭐'},{id:'heart',label:'💖',value:'💖'},{id:'snow',label:'❄️',value:'❄️'}],targets:[{id:'blank',label:'?' }],correct_answer:['⭐'],distractors:['💖','❄️'],hint_1:'Say the pattern aloud.',hint_2:'It repeats star, heart.',hint_3:'After the heart comes a star.',success_feedback:'Yes. The AB pattern repeats star, heart.',retry_feedback:'Look for the part that keeps repeating.',mastery_signal:'Extends an AB pattern using the repeating unit.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Pattern Star',materials:'No materials.',parent:'Ask her to name the repeating unit.',extension:'Try star, heart, heart.'
},
{
 id:'math-add',domain:'math',skill:'Addition with objects',icon:'👑',title:'Royal Gem Addition',character:'Ballroom Princess',character_icon:'👸',objective:'Join two sets and count the total.',reason:'Manipulating objects gives addition a concrete meaning before memorization.',interaction_type:'number_manipulative',instruction_text:'Add 1 gem to 2!',spoken_instruction:'There are two gems. Add one more gem. Then count how many there are altogether.',character_prompt:'Add one gem to my crown!',items:[{id:'g1',label:'Gem',emoji:'💎'},{id:'g2',label:'Gem',emoji:'💎'},{id:'g3',label:'Gem',emoji:'💎'}],targets:[{id:'crown',label:'Crown',emoji:'👑'}],correct_answer:1,distractors:[2,3],hint_1:'Start with two gems.',hint_2:'Add just one more.',hint_3:'Two and one more makes three.',success_feedback:'You added one gem. Two plus one makes three.',retry_feedback:'Start with two, then move one more.',mastery_signal:'Joins one object to a set of two and identifies the total.',difficulty:1,estimated_minutes:3,reward:'✨ Shiny Math Star',materials:'Optional real gems/counters.',parent:'Have her count the final set once.',extension:'Start with 3 and add 2.',initial_count:2,target_total:3
},
{
 id:'language-retell',domain:'language',skill:'Story sequencing',icon:'📚',title:'Unlock the Story Castle',character:'Book Princess',character_icon:'👸📚',objective:'Sequence three story events.',reason:'Ordering events directly demonstrates understanding of temporal story structure.',interaction_type:'sequence',instruction_text:'Put the story in order!',spoken_instruction:'A princess lost a key, looked under a leaf, and found it by a flower. Put the events first, next, and last.',character_prompt:'Put my story back together!',items:[{id:'lost',label:'Lost the key',emoji:'🗝️'},{id:'looked',label:'Looked under a leaf',emoji:'🍃'},{id:'found',label:'Found it by a flower',emoji:'🌸'}],targets:[{id:'first',label:'FIRST'},{id:'next',label:'NEXT'},{id:'last',label:'LAST'}],correct_answer:['lost','looked','found'],distractors:[],hint_1:'What happened before she searched?',hint_2:'She had to lose the key first.',hint_3:'Lost → looked → found.',success_feedback:'You put the story events in time order.',retry_feedback:'Think about what had to happen first.',mastery_signal:'Orders all three events without parent arranging them.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Story Star',materials:'No materials.',parent:'Afterward ask her to retell the story.',extension:'Add one detail about the setting.'
},
{
 id:'language-why',domain:'language',skill:'Explaining reasoning',icon:'📚',title:'Book Princess Why?',character:'Book Princess',character_icon:'👸📚',objective:'Choose and explain a plausible cause.',reason:'A story choice followed by explanation links comprehension with verbal reasoning.',interaction_type:'story_choice',instruction_text:'Why wear boots in rain?',spoken_instruction:'It is raining outside. Why might the princess wear boots?',character_prompt:'Help me choose for the rain!',items:[{id:'dry',label:'Keep feet dry',emoji:'🥾'},{id:'sleep',label:'Go to sleep',emoji:'😴'},{id:'read',label:'Make a book louder',emoji:'📖'}],targets:[],correct_answer:'dry',distractors:['sleep','read'],hint_1:'Think about what rain does.',hint_2:'Rain makes things wet.',hint_3:'Boots can help keep feet dry.',success_feedback:'Yes. Boots can help keep feet dry in rain.',retry_feedback:'Think about what the boots protect from rain.',mastery_signal:'Selects a relevant reason and can explain it in her own words.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Thinking Star',materials:'No materials.',parent:'Ask her to say the reason after choosing.',extension:'Name another thing useful in rain.'
},
{
 id:'logic-odd',domain:'logic',skill:'Categorization',icon:'👑',title:'Royal Sorting Room',character:'Ballroom Princess',character_icon:'👸',objective:'Sort objects into fruit and vegetable groups.',reason:'Sorting by category demonstrates conceptual grouping more directly than a single odd-one-out answer.',interaction_type:'sort',instruction_text:'Sort fruit and vegetables!',spoken_instruction:'Put each food in the fruit basket or the vegetable basket.',character_prompt:'Help sort the royal picnic!',items:[{id:'apple',label:'Apple',emoji:'🍎'},{id:'banana',label:'Banana',emoji:'🍌'},{id:'carrot',label:'Carrot',emoji:'🥕'},{id:'broccoli',label:'Broccoli',emoji:'🥦'}],targets:[{id:'fruit',label:'Fruit',emoji:'🧺'},{id:'veg',label:'Vegetables',emoji:'🥗'}],correct_answer:{apple:'fruit',banana:'fruit',carrot:'veg',broccoli:'veg'},distractors:[],hint_1:'Think about which foods are fruits.',hint_2:'Apple and banana belong together.',hint_3:'Apple and banana are fruit; carrot and broccoli are vegetables.',success_feedback:'You sorted foods by their category.',retry_feedback:'Look for which foods belong together.',mastery_signal:'Correctly classifies four familiar foods by category.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Thinking Star',materials:'No materials.',parent:'Ask how she knew one item belonged.',extension:'Add tomato and discuss why categories can be tricky.'
},
{
 id:'logic-pattern',domain:'logic',skill:'Pattern recognition',icon:'🏰',title:'Tower Princess Pattern',character:'Tower Princess',character_icon:'👸🏰',objective:'Complete an ABB pattern.',reason:'Building a missing pattern element tests recognition of structure.',interaction_type:'pattern_builder',instruction_text:'Finish the tower pattern!',spoken_instruction:'Look: star, heart, heart, star, heart, heart. What comes next?',character_prompt:'Build my next tower tile!',items:[{id:'star',label:'⭐',value:'⭐'},{id:'heart',label:'💖',value:'💖'},{id:'gem',label:'💎',value:'💎'}],targets:[{id:'blank',label:'?'}],correct_answer:['⭐'],distractors:['💖','💎'],hint_1:'Say the groups slowly.',hint_2:'Each group is star, heart, heart.',hint_3:'A new group starts with star.',success_feedback:'You found the ABB pattern: star, heart, heart.',retry_feedback:'Find the three-part chunk that repeats.',mastery_signal:'Identifies the repeating ABB unit and extends it.',difficulty:3,estimated_minutes:4,reward:'✨ Shiny Pattern Star',materials:'No materials.',parent:'Ask what three things repeat.',extension:'Build an AAB pattern.'
},
{
 id:'science-habitat',domain:'science',skill:'Animals & habitats',icon:'🧜‍♀️',title:'Mermaid Habitat Match',character:'Mermaid Princess',character_icon:'🧜‍♀️',objective:'Match animals to familiar habitats.',reason:'Matching requires connecting an animal with relevant environmental knowledge.',interaction_type:'match',instruction_text:'Match animals to homes!',spoken_instruction:'Match each animal to the place where it usually lives.',character_prompt:'Help my animal friends home!',items:[{id:'fish',label:'Fish',emoji:'🐟'},{id:'bird',label:'Bird',emoji:'🐦'},{id:'camel',label:'Camel',emoji:'🐪'}],targets:[{id:'ocean',label:'Ocean',emoji:'🌊'},{id:'nest',label:'Nest',emoji:'🪺'},{id:'desert',label:'Desert',emoji:'🏜️'}],correct_answer:{fish:'ocean',bird:'nest',camel:'desert'},distractors:[],hint_1:'Think about where each animal gets what it needs.',hint_2:'Fish need water.',hint_3:'Fish-ocean, bird-nest, camel-desert.',success_feedback:'You matched each animal with a fitting habitat.',retry_feedback:'Think about where that animal usually lives.',mastery_signal:'Matches three familiar animals to habitats.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Science Star',materials:'No materials.',parent:'Ask one “why” question after matching.',extension:'Where might a frog live?'
},
{
 id:'science-float',domain:'science',skill:'Prediction',icon:'🧜‍♀️',title:'Mermaid Float-or-Sink Lab',character:'Mermaid Princess',character_icon:'🧜‍♀️',objective:'Predict, test, observe, and compare results.',reason:'The child practices the scientific process rather than memorizing outcomes.',interaction_type:'offline_activity',instruction_text:'Predict. Test. See what happens!',spoken_instruction:'Choose three safe objects. Before each one goes in water, predict whether it will float or sink. Then test it.',character_prompt:'What will my objects do?',items:[{id:'object1',label:'Safe object 1'},{id:'object2',label:'Safe object 2'},{id:'object3',label:'Safe object 3'}],targets:[{id:'float',label:'Float'},{id:'sink',label:'Sink'}],correct_answer:'parent_observation',distractors:[],hint_1:'Make a guess before testing.',hint_2:'Look carefully at what the object does.',hint_3:'Say: I predicted __, but I observed __.',success_feedback:'You used a scientist cycle: predict, test, observe.',retry_feedback:'Try one object at a time and say your prediction first.',mastery_signal:'Makes predictions and accurately reports observed outcomes.',difficulty:2,estimated_minutes:6,reward:'✨ Shiny Science Star',materials:'Bowl of water and 3 safe waterproof objects; adult supervision.',parent:'Prediction accuracy is not the goal; noticing evidence is.',extension:'Choose a fourth object and explain the prediction.'
},
{
 id:'memory-match',domain:'memory',skill:'Visual memory',icon:'✨',title:'Princess Memory Stars',character:'Fairy Guide',character_icon:'🧚',objective:'Remember card locations to make pairs.',reason:'Small card-pair sets exercise visual memory and attention.',interaction_type:'memory',instruction_text:'Find the matching pairs!',spoken_instruction:'Flip two cards at a time. Remember where the pictures are and find all the matching pairs.',character_prompt:'Find my shiny matching stars!',items:[{id:'star1',pair:'star',label:'⭐'},{id:'star2',pair:'star',label:'⭐'},{id:'crown1',pair:'crown',label:'👑'},{id:'crown2',pair:'crown',label:'👑'},{id:'gem1',pair:'gem',label:'💎'},{id:'gem2',pair:'gem',label:'💎'}],targets:[],correct_answer:['star','crown','gem'],distractors:[],hint_1:'Remember where you saw each picture.',hint_2:'Try to recall one card you already flipped.',hint_3:'Slow down and look at only one pair at a time.',success_feedback:'You used visual memory to find the pairs.',retry_feedback:'Keep watching where each picture hides.',mastery_signal:'Completes three pairs with decreasing repeat flips.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Memory Star',materials:'No materials.',parent:'Let her play without naming every location for her.',extension:'Add one more pair later.'
},
{
 id:'executive-switch',domain:'executive',skill:'Rule switching',icon:'❄️',title:'Ice Princess Rule Switch',character:'Ice Princess',character_icon:'👸❄️',objective:'Switch between two simple movement rules.',reason:'Changing response rules practices cognitive flexibility and inhibition.',interaction_type:'movement',instruction_text:'Clap for sun. Tap for moon!',spoken_instruction:'When I say sun, clap. When I say moon, touch your head. After a few turns, switch the rules.',character_prompt:'Can you switch my magic rule?',items:[{id:'sun',label:'Sun',action:'clap'},{id:'moon',label:'Moon',action:'touch head'}],targets:[{id:'clap',label:'Clap'},{id:'head',label:'Touch head'}],correct_answer:'parent_observation',distractors:[],hint_1:'Say the rule once more.',hint_2:'Practice one sun and one moon slowly.',hint_3:'Model one switched turn together.',success_feedback:'You changed rules and kept the new rule in mind.',retry_feedback:'Slow down. Say the new rule before you move.',mastery_signal:'Follows the switched rule on most trials after no more than one reminder.',difficulty:3,estimated_minutes:4,reward:'✨ Shiny Focus Star',materials:'Safe movement space.',parent:'After 4 turns, reverse the two rules.',extension:'Add star = jump only if easy.'
},
{
 id:'sel-feelings',domain:'sel',skill:'Emotion identification',icon:'👑',title:'Ballroom Feelings Story',character:'Ballroom Princess',character_icon:'👸',objective:'Choose a plausible feeling and helpful response.',reason:'Story-based choices connect emotion vocabulary to real coping actions.',interaction_type:'story_choice',instruction_text:'How might she feel?',spoken_instruction:'A child built a tower and it fell down. How might she feel?',character_prompt:'Help me understand her feeling.',items:[{id:'sad',label:'Sad or frustrated',emoji:'😟'},{id:'sleepy',label:'Sleepy',emoji:'😴'},{id:'silly',label:'Silly for no reason',emoji:'🤪'}],targets:[],correct_answer:'sad',distractors:['sleepy','silly'],hint_1:'Think about losing something you worked on.',hint_2:'She may feel upset because the tower fell.',hint_3:'Sad or frustrated fits the story.',success_feedback:'Yes. Losing a tower can feel sad or frustrating. We can try again or ask for help.',retry_feedback:'Think about how you might feel if your work fell down.',mastery_signal:'Selects a plausible emotion and names one helpful next action.',difficulty:1,estimated_minutes:3,reward:'✨ Shiny Kindness Star',materials:'No materials.',parent:'After choosing, ask what could help.',extension:'Name another possible feeling.'
},
{
 id:'life-cleanup',domain:'life',skill:'Cleaning up',icon:'👑',title:'Royal Reset Sequence',character:'Ballroom Princess',character_icon:'👸',objective:'Complete a three-step cleanup routine in order.',reason:'Sequenced real-world action builds planning, organization, and task completion.',interaction_type:'offline_activity',instruction_text:'Toys. Books. Check the floor!',spoken_instruction:'Put toys in their homes, place books together, then check the floor.',character_prompt:'Help reset the royal room!',items:[{id:'toys',label:'Put toys away'},{id:'books',label:'Place books together'},{id:'check',label:'Check the floor'}],targets:[{id:'first',label:'First'},{id:'next',label:'Next'},{id:'last',label:'Last'}],correct_answer:['toys','books','check'],distractors:[],hint_1:'Do one small step at a time.',hint_2:'Start with the toys.',hint_3:'Toys, then books, then floor check.',success_feedback:'You finished a real three-step routine.',retry_feedback:'Make the cleanup area smaller and finish one step first.',mastery_signal:'Completes the 3-step routine with no more than one reminder.',difficulty:2,estimated_minutes:4,reward:'✨ Shiny Independence Star',materials:'One small real cleanup area.',parent:'Keep the area small enough to finish successfully.',extension:'Let her choose the order next time and explain it.'
},
{
 id:'writing-trace',domain:'writing',skill:'Letter formation',icon:'📚',title:'Trace the Magic S',character:'Book Princess',character_icon:'👸📚',objective:'Trace a large S using continuous controlled movement.',reason:'A guided path supports directionality and motor planning without excessive tracing.',interaction_type:'trace',instruction_text:'Trace the shiny S!',spoken_instruction:'Start at the shiny star and trace the big S path slowly.',character_prompt:'Trace my library letter!',items:[{id:'path',label:'S path',points:[[75,30],[45,20],[25,40],[45,60],[70,65],[80,85],[55,105],[25,95]]}],targets:[{id:'end',label:'Finish star'}],correct_answer:'trace_path',distractors:[],hint_1:'Start at the top star.',hint_2:'Curve around, then curve back.',hint_3:'Follow the dotted path slowly.',success_feedback:'Your finger followed the S curve from start to finish.',retry_feedback:'Try again slowly and stay close to the path.',mastery_signal:'Traces the S path with sustained direction and control.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Writing Star',materials:'Optional stylus or finger.',parent:'One or two careful traces are enough.',extension:'Make S with your arm in the air.'
},
{
 id:'fine-sort',domain:'fine',skill:'Pincer control',icon:'✨',title:'Shiny Gem Rescue',character:'Fairy Guide',character_icon:'🧚',objective:'Transfer small safe objects using pincer grasp.',reason:'Purposeful finger control strengthens precision used for pencils and scissors.',interaction_type:'offline_activity',instruction_text:'Move 10 gems with two fingers!',spoken_instruction:'Use your thumb and pointer finger to move ten safe pom-poms or large buttons into two cups.',character_prompt:'Rescue my tiny shiny gems!',items:[{id:'gems',label:'10 safe large gems/pom-poms'}],targets:[{id:'cup1',label:'Cup 1'},{id:'cup2',label:'Cup 2'}],correct_answer:'parent_observation',distractors:[],hint_1:'Use thumb and pointer finger.',hint_2:'Move one at a time.',hint_3:'Parent models one controlled pinch.',success_feedback:'You used careful finger control to move the gems.',retry_feedback:'Use larger objects and slow down the pinch.',mastery_signal:'Transfers objects with controlled pincer grasp and minimal dropping.',difficulty:1,estimated_minutes:4,reward:'✨ Shiny Fine-Motor Star',materials:'Large buttons/pom-poms and two cups; supervise.',parent:'Avoid small choking-hazard items.',extension:'Sort by color while transferring.'
},
{
 id:'gross-sequence',domain:'gross',skill:'Movement sequences',icon:'👑',title:'Princess Movement Code',character:'Tower Princess',character_icon:'👸🏰',objective:'Remember and perform a three-action sequence.',reason:'Movement sequencing combines gross-motor coordination and working memory.',interaction_type:'movement',instruction_text:'Clap. Jump. Touch knees!',spoken_instruction:'Watch and remember: clap, jump, touch your knees. Now do the whole movement code.',character_prompt:'Copy my tower movement code!',items:[{id:'clap',label:'Clap',emoji:'👏'},{id:'jump',label:'Jump',emoji:'⬆️'},{id:'knees',label:'Touch knees',emoji:'🦵'}],targets:[{id:'sequence',label:'Movement sequence'}],correct_answer:['clap','jump','knees'],distractors:[],hint_1:'Hear the three moves again.',hint_2:'First clap, then jump.',hint_3:'Clap → jump → touch knees.',success_feedback:'You remembered all three movements in order.',retry_feedback:'Try only two moves first, then add the third.',mastery_signal:'Performs the 3-movement sequence correctly on most attempts.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Movement Star',materials:'Safe open floor space.',parent:'Reduce to two movements if needed.',extension:'Let her invent a sequence for you.'
},
{
 id:'knowledge-match',domain:'knowledge',skill:'Community knowledge',icon:'📚',title:'Who Helps Us?',character:'Book Princess',character_icon:'👸📚',objective:'Match community helpers with familiar roles.',reason:'Matching roles builds useful background knowledge and vocabulary.',interaction_type:'match',instruction_text:'Match helpers to their jobs!',spoken_instruction:'Match each helper to what they help people do.',character_prompt:'Help organize my helper book!',items:[{id:'firefighter',label:'Firefighter',emoji:'🧑‍🚒'},{id:'librarian',label:'Librarian',emoji:'🧑‍🏫'},{id:'doctor',label:'Doctor',emoji:'🧑‍⚕️'}],targets:[{id:'fire',label:'Helps with fires',emoji:'🚒'},{id:'books',label:'Helps find books',emoji:'📚'},{id:'health',label:'Helps when we are sick',emoji:'🩺'}],correct_answer:{firefighter:'fire',librarian:'books',doctor:'health'},distractors:[],hint_1:'Think about where you see each helper.',hint_2:'A librarian works with books.',hint_3:'Firefighter-fire, librarian-books, doctor-health.',success_feedback:'You matched each helper to an important job.',retry_feedback:'Think about what that helper usually does.',mastery_signal:'Matches three community helpers with familiar roles.',difficulty:1,estimated_minutes:4,reward:'✨ Shiny Knowledge Star',materials:'No materials.',parent:'Name a trusted adult the child can ask for help.',extension:'Add teacher or police officer.'
},
{
 id:'creativity-story',domain:'creativity',skill:'Story creation',icon:'🏰',title:'Tower Princess Story Builder',character:'Tower Princess',character_icon:'👸🏰',objective:'Choose story parts and tell a connected mini-story.',reason:'Constructing a story with character, problem, and solution organizes imagination into causal language.',interaction_type:'multi_select',instruction_text:'Pick 3 story magic pieces!',spoken_instruction:'Pick one character, one problem, and one solution. Then tell your mini-story.',character_prompt:'Build a tiny tower tale!',items:[{id:'princess',label:'Tower princess',group:'character',emoji:'👸'},{id:'unicorn',label:'Unicorn',group:'character',emoji:'🦄'},{id:'lostkey',label:'Lost a key',group:'problem',emoji:'🗝️'},{id:'rain',label:'Rain blocked the path',group:'problem',emoji:'🌧️'},{id:'map',label:'Used a map',group:'solution',emoji:'🗺️'},{id:'friend',label:'Asked a friend',group:'solution',emoji:'🤝'}],targets:[{id:'character',label:'Character'},{id:'problem',label:'Problem'},{id:'solution',label:'Solution'}],correct_answer:{rule:'one_per_group',groups:['character','problem','solution']},distractors:[],hint_1:'Pick one from each kind.',hint_2:'You need a character, problem, and solution.',hint_3:'Choose one person, one trouble, and one way to fix it.',success_feedback:'You chose the three parts a story needs. Now tell how they connect.',retry_feedback:'Make sure you picked one character, one problem, and one solution.',mastery_signal:'Selects all three story functions and orally connects them.',difficulty:2,estimated_minutes:5,reward:'✨ Shiny Creativity Star',materials:'Optional paper for drawing.',parent:'Follow her ideas; do not take over the story.',extension:'Draw and label the ending.'
},
{
 id:'find-shapes',domain:'math',skill:'Shapes & spatial reasoning',icon:'👑',title:'Castle Shape Hunt',character:'Ballroom Princess',character_icon:'👸',objective:'Find all circles in a mixed visual scene.',reason:'Visual search for a target property demonstrates shape recognition in varied objects.',interaction_type:'find_it',instruction_text:'Find all 3 circles!',spoken_instruction:'Find and tap all three circle shapes hiding in the castle room.',character_prompt:'Find my hidden circle treasures!',items:[{id:'clock',label:'Clock',emoji:'🕒',is_correct:true},{id:'window',label:'Round window',emoji:'🔵',is_correct:true},{id:'plate',label:'Plate',emoji:'🍽️',is_correct:true},{id:'book',label:'Book',emoji:'📕',is_correct:false},{id:'door',label:'Door',emoji:'🚪',is_correct:false},{id:'kite',label:'Kite',emoji:'🪁',is_correct:false}],targets:[{id:'scene',label:'Castle room'}],correct_answer:['clock','window','plate'],distractors:['book','door','kite'],hint_1:'Look for round shapes.',hint_2:'A circle has no corners.',hint_3:'Clock, round window, and plate are circles.',success_feedback:'You found all the round shapes with no corners.',retry_feedback:'Look for objects that are round all the way around.',mastery_signal:'Finds all target circles while ignoring non-circles.',difficulty:2,estimated_minutes:3,reward:'✨ Shiny Shape Star',materials:'No materials.',parent:'Ask what makes a circle different from a square.',extension:'Find a real circle in the room.'
}
];

function validateStructuredActivity(a){
 const required=['interaction_type','instruction_text','spoken_instruction','character_prompt','items','targets','correct_answer','distractors','hint_1','hint_2','hint_3','success_feedback','retry_feedback','mastery_signal','difficulty','estimated_minutes'];
 if(!a||!ALLOWED_INTERACTIONS.has(a.interaction_type))return false;
 if(required.some(k=>a[k]===undefined||a[k]===null))return false;
 if(!Array.isArray(a.items)||!Array.isArray(a.targets)||!Array.isArray(a.distractors))return false;
 if(!['movement','offline_activity'].includes(a.interaction_type)&&a.items.length===0)return false;
 if(a.difficulty<1||a.difficulty>5||a.estimated_minutes<=0)return false;
 const ids=new Set(a.items.map(i=>i.id));
 if(['tap_choice','story_choice'].includes(a.interaction_type)&&!ids.has(a.correct_answer))return false;
 if(a.interaction_type==='multi_select'&&a.correct_answer.rule!=='one_per_group'&&(!Array.isArray(a.correct_answer)||a.correct_answer.some(x=>!ids.has(x))))return false;
 if(['sequence'].includes(a.interaction_type)&&(!Array.isArray(a.correct_answer)||a.correct_answer.some(x=>!ids.has(x))))return false;
 if(['sort','match','drag_drop'].includes(a.interaction_type)){const targetIds=new Set(a.targets.map(t=>t.id));if(Object.entries(a.correct_answer).some(([item,target])=>!ids.has(item)||!targetIds.has(target)))return false;}
 return true;
}

const rejectedActivities=structuredActivities.filter(a=>!validateStructuredActivity(a));
if(rejectedActivities.length)console.error('Rejected invalid learning activities:',rejectedActivities.map(a=>a.id));
const validActivities=structuredActivities.filter(validateStructuredActivity);
activities.splice(0,activities.length,...validActivities);
if(themes.dragon)delete themes.dragon;
if(data.theme==='dragon')data.theme='unicorn';
data.interactionEvidence=data.interactionEvidence||[];
data.shinyStars=data.shinyStars||0;
persist(false);

let interactionRuntime=null;
function speakInstruction(text){
 if(!('speechSynthesis' in window))return;
 window.speechSynthesis.cancel();
 const u=new SpeechSynthesisUtterance(text);u.rate=.86;u.pitch=1.08;u.lang='en-US';window.speechSynthesis.speak(u);
}
function shinyProgress(){
 const ids=data.quest||[];return `<div class="shiny-progress" aria-label="Quest progress">${ids.map(id=>data.questResults[id]!=null?'<span class="filled">⭐</span>':'<span>☆</span>').join('')}</div>`;
}
function runtimeState(){return interactionRuntime?interactionRuntime.state:{};}
function startRuntime(a,containerId,source){interactionRuntime={activity:a,containerId,source,attempts:0,hintLevel:0,startedAt:Date.now(),lastActionAt:0,fastActions:0,state:{selected:new Set(),placements:{},order:[],flipped:[],matched:new Set(),tracePoints:[],count:0}};}
function openStructuredActivity(a,containerId,source){
 if(!validateStructuredActivity(a)){document.getElementById(containerId).innerHTML='<div class="completion">This activity needs adult review before it can run.</div>';return;}
 startRuntime(a,containerId,source);const el=document.getElementById(containerId);el.classList.add('active');
 el.innerHTML=`<div class="child-mission"><div class="mission-top">${shinyProgress()}<button class="child-close" onclick="closeStructuredActivity()">🏠 Home</button></div><div class="character-guide"><div class="character-avatar">${a.character_icon||'✨'}</div><div><small>${esc(a.character||'Magic Guide')}</small><b>${esc(a.character_prompt)}</b></div></div><div class="child-instruction">${esc(a.instruction_text)}</div><div class="child-tools"><button class="child-tool hear" onclick="hearCurrent()">🔊 Hear It</button><button class="child-tool hint" onclick="showHint()">💡 Hint</button></div><div id="structuredHint" class="structured-hint"></div><div id="interactionMount"></div><div id="structuredFeedback" class="structured-feedback"></div></div>`;
 renderInteraction(a);el.scrollIntoView({behavior:'smooth',block:'start'});
}
function runActivity(id){const a=activities.find(x=>x.id===id);if(a)openStructuredActivity(a,'activityRunner','quest');}
function runLearningActivity(id){const a=activities.find(x=>x.id===id);if(a)openStructuredActivity(a,'learnRunner','learn');}
function closeStructuredActivity(){if(!interactionRuntime)return;const el=document.getElementById(interactionRuntime.containerId);el.classList.remove('active');el.innerHTML='';interactionRuntime=null;}
function closeActivity(){closeStructuredActivity();}
function hearCurrent(){if(interactionRuntime)speakInstruction(interactionRuntime.activity.spoken_instruction);}
function showHint(){if(!interactionRuntime)return;const r=interactionRuntime,a=r.activity;r.hintLevel=Math.min(3,r.hintLevel+1);const text=a['hint_'+r.hintLevel];document.getElementById('structuredHint').textContent='💡 '+text;speakInstruction(text);recordInteractionEvent('hint',{level:r.hintLevel});if(r.hintLevel===3)applyStrongScaffold();}
function applyStrongScaffold(){const mount=document.getElementById('interactionMount');if(mount)mount.classList.add('strong-scaffold');}
function recordInteractionEvent(type,extra={}){if(!interactionRuntime)return;data.interactionEvidence.push({date:todayKey(),activityId:interactionRuntime.activity.id,interaction_type:interactionRuntime.activity.interaction_type,type,attempts:interactionRuntime.attempts,hintLevel:interactionRuntime.hintLevel,elapsed:Math.round((Date.now()-interactionRuntime.startedAt)/1000),...extra});data.interactionEvidence=data.interactionEvidence.slice(-180);persist(false);}
function actionPulse(){if(!interactionRuntime)return false;const now=Date.now();if(interactionRuntime.lastActionAt&&now-interactionRuntime.lastActionAt<320)interactionRuntime.fastActions++;else interactionRuntime.fastActions=Math.max(0,interactionRuntime.fastActions-1);interactionRuntime.lastActionAt=now;if(interactionRuntime.fastActions>=3){document.getElementById('structuredFeedback').textContent='✨ Slow detective mode — look, think, then tap.';recordInteractionEvent('possible_random_tapping');return true}return false;}
function renderInteraction(a){const m=document.getElementById('interactionMount');m.innerHTML='';switch(a.interaction_type){case'tap_choice':case'story_choice':renderTapChoice(a,m);break;case'multi_select':renderMultiSelect(a,m);break;case'sort':case'drag_drop':renderSort(a,m);break;case'match':renderMatch(a,m);break;case'memory':renderMemory(a,m);break;case'sequence':renderSequence(a,m);break;case'word_builder':renderWordBuilder(a,m);break;case'number_manipulative':renderNumberManipulator(a,m);break;case'pattern_builder':renderPatternBuilder(a,m);break;case'find_it':renderFindIt(a,m);break;case'trace':renderTrace(a,m);break;case'movement':case'offline_activity':renderOffline(a,m);break;default:m.textContent='Interaction unavailable.';}}
function itemButton(i,extra=''){return `<button class="touch-item ${extra}" data-id="${esc(i.id)}">${i.emoji?`<span>${i.emoji}</span>`:''}<b>${esc(i.label||i.value||i.id)}</b></button>`;}
function renderTapChoice(a,m){m.innerHTML=`<div class="touch-grid">${shuffle(a.items).map(i=>itemButton(i,'choice-touch')).join('')}</div>`;m.querySelectorAll('.choice-touch').forEach(b=>b.onclick=()=>submitTap(b.dataset.id,b));}
function submitTap(id,btn){if(actionPulse())return;interactionRuntime.attempts++;const a=interactionRuntime.activity;if(id===a.correct_answer){btn.classList.add('correct');finishSuccess();}else{btn.classList.add('gentle-wrong');handleRetry();}}
function renderMultiSelect(a,m){m.innerHTML=`<div class="touch-grid">${shuffle(a.items).map(i=>itemButton(i,'multi-touch')).join('')}</div><button class="big-action" onclick="checkMultiSelect()">⭐ Check My Picks</button>`;m.querySelectorAll('.multi-touch').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');const s=runtimeState().selected;b.classList.contains('selected')?s.add(b.dataset.id):s.delete(b.dataset.id);});}
function checkMultiSelect(){const a=interactionRuntime.activity,s=[...runtimeState().selected];interactionRuntime.attempts++;let ok=false;if(a.correct_answer.rule==='one_per_group'){const groups=a.correct_answer.groups;ok=groups.every(g=>s.filter(id=>a.items.find(i=>i.id===id)?.group===g).length===1)&&s.length===groups.length;}else ok=s.length===a.correct_answer.length&&a.correct_answer.every(x=>s.includes(x));ok?finishSuccess():handleRetry();}
function renderSort(a,m){m.innerHTML=`<div class="drag-source">${shuffle(a.items).map(i=>`<div class="draggable-wrap">${itemButton(i,'drag-item')}</div>`).join('')}</div><div class="target-grid">${a.targets.map(t=>`<button class="drop-target" data-target="${esc(t.id)}"><span>${t.emoji||'✨'}</span><b>${esc(t.label)}</b><div class="placed"></div></button>`).join('')}</div><div class="tap-fallback">Tap an item, then tap its home.</div><button class="big-action" onclick="checkPlacements()">⭐ Check My Sort</button>`;enableDragTap(m);}
function enableDragTap(m){let selected=null;m.querySelectorAll('.drag-item').forEach(b=>{b.draggable=true;b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.id));b.onclick=()=>{selected=b.dataset.id;m.querySelectorAll('.drag-item').forEach(x=>x.classList.toggle('selected',x.dataset.id===selected));}});m.querySelectorAll('.drop-target').forEach(t=>{t.addEventListener('dragover',e=>e.preventDefault());t.addEventListener('drop',e=>{e.preventDefault();placeItem(e.dataTransfer.getData('text/plain'),t.dataset.target,m)});t.onclick=()=>{if(selected){placeItem(selected,t.dataset.target,m);selected=null;}}});}
function placeItem(itemId,targetId,m){runtimeState().placements[itemId]=targetId;const item=interactionRuntime.activity.items.find(i=>i.id===itemId);const target=m.querySelector(`[data-target="${CSS.escape(targetId)}"] .placed`);if(target&&!target.querySelector(`[data-placed="${CSS.escape(itemId)}"]`)){m.querySelector(`[data-id="${CSS.escape(itemId)}"]`)?.classList.add('placed-away');target.insertAdjacentHTML('beforeend',`<span class="placed-chip" data-placed="${esc(itemId)}">${item?.emoji||''} ${esc(item?.label||itemId)}</span>`);}}
function checkPlacements(){const a=interactionRuntime.activity,p=runtimeState().placements;interactionRuntime.attempts++;const ok=Object.keys(a.correct_answer).every(id=>p[id]===a.correct_answer[id])&&Object.keys(p).length===Object.keys(a.correct_answer).length;ok?finishSuccess():handleRetry();}
function renderMatch(a,m){m.innerHTML=`<div class="match-cols"><div>${a.items.map(i=>itemButton(i,'match-left')).join('')}</div><div>${shuffle(a.targets).map(t=>`<button class="touch-item match-right" data-id="${esc(t.id)}">${t.emoji?`<span>${t.emoji}</span>`:''}<b>${esc(t.label)}</b></button>`).join('')}</div></div><div class="match-status" id="matchStatus"></div>`;let left=null;m.querySelectorAll('.match-left').forEach(b=>b.onclick=()=>{left=b.dataset.id;m.querySelectorAll('.match-left').forEach(x=>x.classList.toggle('selected',x.dataset.id===left));});m.querySelectorAll('.match-right').forEach(b=>b.onclick=()=>{if(!left)return;interactionRuntime.attempts++;const ok=a.correct_answer[left]===b.dataset.id;if(ok){runtimeState().matched.add(left);m.querySelector(`[data-id="${CSS.escape(left)}"]`).classList.add('correct');b.classList.add('correct');document.getElementById('matchStatus').textContent='✨ Match found!';if(runtimeState().matched.size===a.items.length)finishSuccess();}else{b.classList.add('gentle-wrong');handleRetry(false);}left=null;});}
function renderMemory(a,m){m.innerHTML=`<div class="memory-grid">${shuffle(a.items).map(i=>`<button class="memory-card" data-id="${esc(i.id)}" data-pair="${esc(i.pair)}"><span class="back">⭐</span><span class="front">${esc(i.label)}</span></button>`).join('')}</div>`;m.querySelectorAll('.memory-card').forEach(b=>b.onclick=()=>flipMemory(b));}
function flipMemory(b){const st=runtimeState();if(st.flipped.length>=2||b.classList.contains('matched'))return;b.classList.add('flipped');st.flipped.push(b);if(st.flipped.length===2){interactionRuntime.attempts++;const[x,y]=st.flipped;if(x.dataset.pair===y.dataset.pair){x.classList.add('matched');y.classList.add('matched');st.matched.add(x.dataset.pair);st.flipped=[];if(st.matched.size===interactionRuntime.activity.correct_answer.length)finishSuccess();}else setTimeout(()=>{x.classList.remove('flipped');y.classList.remove('flipped');st.flipped=[];},700);}}
function renderSequence(a,m){const order=shuffle(a.items.map(i=>i.id));runtimeState().order=order;m.innerHTML=`<div class="sequence-list" id="sequenceList"></div><button class="big-action" onclick="checkSequence()">⭐ Check My Order</button>`;renderSequenceList();}
function renderSequenceList(){const a=interactionRuntime.activity,box=document.getElementById('sequenceList');if(!box)return;box.innerHTML=runtimeState().order.map((id,idx)=>{const i=a.items.find(x=>x.id===id);return `<div class="sequence-card"><span>${i.emoji||'✨'}</span><b>${esc(i.label)}</b><div><button onclick="moveSequence(${idx},-1)">⬆️</button><button onclick="moveSequence(${idx},1)">⬇️</button></div></div>`}).join('');}
function moveSequence(i,d){const o=runtimeState().order,j=i+d;if(j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];renderSequenceList();}
function checkSequence(){interactionRuntime.attempts++;const a=interactionRuntime.activity,o=runtimeState().order;const ok=o.length===a.correct_answer.length&&o.every((x,i)=>x===a.correct_answer[i]);ok?finishSuccess():handleRetry();}
function renderWordBuilder(a,m){runtimeState().order=[];m.innerHTML=`<div class="word-slots">${a.targets.map((_,i)=>`<button class="word-slot" data-slot="${i}">_</button>`).join('')}</div><div class="letter-bank">${shuffle(a.items).map(i=>itemButton(i,'letter-tile')).join('')}</div><div class="tap-fallback">Tap letters in sound order.</div><button class="big-action" onclick="checkWord()">⭐ Check My Word</button>`;m.querySelectorAll('.letter-tile').forEach(b=>b.onclick=()=>{if(runtimeState().order.length>=a.targets.length)return;const item=a.items.find(i=>i.id===b.dataset.id);runtimeState().order.push(item.value);b.disabled=true;renderWordSlots();});m.querySelectorAll('.word-slot').forEach(b=>b.onclick=()=>{const idx=+b.dataset.slot;if(idx<runtimeState().order.length){runtimeState().order.splice(idx,1);m.querySelectorAll('.letter-tile').forEach(x=>x.disabled=false);runtimeState().order.forEach(v=>{const tile=[...m.querySelectorAll('.letter-tile')].find(x=>a.items.find(i=>i.id===x.dataset.id)?.value===v&&!x.disabled);if(tile)tile.disabled=true;});renderWordSlots();}});}
function renderWordSlots(){document.querySelectorAll('#interactionMount .word-slot').forEach((s,i)=>s.textContent=runtimeState().order[i]||'_');}
function checkWord(){interactionRuntime.attempts++;const a=interactionRuntime.activity,o=runtimeState().order;const ok=o.length===a.correct_answer.length&&o.every((x,i)=>x===a.correct_answer[i]);ok?finishSuccess():handleRetry();}
function renderNumberManipulator(a,m){runtimeState().count=0;m.innerHTML=`<div class="number-scene"><div class="already"><small>Already has</small><div>${Array.from({length:a.initial_count||0},()=>'<span>💎</span>').join('')}</div><b>${a.initial_count||0}</b></div><div class="number-target">${a.targets[0]?.emoji||'👑'}<b>${esc(a.targets[0]?.label||'Target')}</b><div id="movedObjects"></div></div></div><div class="manip-bank">${a.items.map(i=>`<button class="manip" onclick="toggleManip(this)">${i.emoji||'💎'}</button>`).join('')}</div><button class="big-action" onclick="checkNumberManip()">⭐ Check My Number</button>`;}
function toggleManip(b){b.classList.toggle('moved');runtimeState().count=[...document.querySelectorAll('#interactionMount .manip.moved')].length;document.getElementById('movedObjects').textContent=Array.from({length:runtimeState().count},()=> '💎').join(' ');}
function checkNumberManip(){interactionRuntime.attempts++;runtimeState().count===interactionRuntime.activity.correct_answer?finishSuccess():handleRetry();}
function renderPatternBuilder(a,m){runtimeState().order=[];const example=a.id==='math-pattern'?'⭐ 💖 ⭐ 💖':'⭐ 💖 💖 ⭐ 💖 💖';m.innerHTML=`<div class="pattern-example">${example} <span class="pattern-blank">?</span></div><div class="touch-grid">${a.items.map(i=>itemButton(i,'pattern-option')).join('')}</div>`;m.querySelectorAll('.pattern-option').forEach(b=>b.onclick=()=>{const i=a.items.find(x=>x.id===b.dataset.id);runtimeState().order=[i.value];interactionRuntime.attempts++;i.value===a.correct_answer[0]?finishSuccess():handleRetry();});}
function renderFindIt(a,m){runtimeState().selected=new Set();m.innerHTML=`<div class="find-scene">${shuffle(a.items).map(i=>`<button class="find-object" data-id="${esc(i.id)}"><span>${i.emoji}</span><b>${esc(i.label)}</b></button>`).join('')}</div><button class="big-action" onclick="checkFindIt()">⭐ I Found Them</button>`;m.querySelectorAll('.find-object').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?runtimeState().selected.add(b.dataset.id):runtimeState().selected.delete(b.dataset.id);});}
function checkFindIt(){interactionRuntime.attempts++;const s=[...runtimeState().selected],a=interactionRuntime.activity;const ok=s.length===a.correct_answer.length&&a.correct_answer.every(x=>s.includes(x));ok?finishSuccess():handleRetry();}
function renderTrace(a,m){m.innerHTML=`<div class="trace-wrap"><canvas id="traceCanvas" width="320" height="180"></canvas></div><div class="row center"><button class="child-tool" onclick="clearTrace()">↻ Try Again</button><button class="big-action inline" onclick="checkTrace()">⭐ Finished</button></div>`;setupTraceCanvas(a);}
function setupTraceCanvas(a){const c=document.getElementById('traceCanvas'),ctx=c.getContext('2d'),pts=a.items[0].points.map(([x,y])=>[x*2.4,y*1.35]);ctx.lineWidth=18;ctx.lineCap='round';ctx.strokeStyle='#eadcf8';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.fillStyle='#ffd84d';ctx.font='28px sans-serif';ctx.fillText('⭐',pts[0][0]-12,pts[0][1]+8);let drawing=false,last=null;c.onpointerdown=e=>{drawing=true;last=pos(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.strokeStyle='#9b5de5';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...p);ctx.stroke();last=p;runtimeState().tracePoints.push(p)};c.onpointerup=()=>drawing=false;function pos(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}}
function clearTrace(){renderTrace(interactionRuntime.activity,document.getElementById('interactionMount'));}
function checkTrace(){interactionRuntime.attempts++;runtimeState().tracePoints.length>=18?finishSuccess():handleRetry();}
function renderOffline(a,m){m.innerHTML=`<div class="offline-card"><div class="offline-icon">${a.interaction_type==='movement'?'🏃‍♀️':'🏡'}</div><p>${esc(a.spoken_instruction)}</p></div><div class="rating"><button onclick="finishParentRated(1)">✨ I did it!</button><button onclick="finishParentRated(.65)">🤝 With help</button><button onclick="finishParentRated(.2)">🌱 Not yet</button></div>`;}
function finishParentRated(score){interactionRuntime.attempts++;if(score>=.6)finishSuccess(score);else finishAttempt(score);}
function handleRetry(allowHint=true){const r=interactionRuntime;r.attempts++;const a=r.activity;document.getElementById('structuredFeedback').textContent='🌈 '+a.retry_feedback;recordInteractionEvent('retry');if(r.attempts>=2&&allowHint&&r.hintLevel<2)showHint();if(r.attempts>=3){r.hintLevel=3;document.getElementById('structuredHint').textContent='💡 '+a.hint_3;applyStrongScaffold();}}
function finishSuccess(forcedScore=null){const r=interactionRuntime,a=r.activity;const score=forcedScore??Math.max(.55,1-(r.attempts>1?(r.attempts-1)*.12:0)-r.hintLevel*.10);document.getElementById('structuredFeedback').innerHTML=`<div class="success-burst"><span class="shiny-star">⭐</span><b>${esc(a.success_feedback)}</b><small>${esc(a.reward||'✨ Shiny Star')}</small></div>`;recordInteractionEvent('success',{score});completeStructured(a,score);}
function finishAttempt(score){const a=interactionRuntime.activity;document.getElementById('structuredFeedback').textContent='🌱 '+a.retry_feedback;recordInteractionEvent('not_yet',{score});completeStructured(a,score);}
function completeStructured(a,score){recordEvidence(a,score);if(interactionRuntime.source==='quest'){data.questResults[a.id]=score;data.questHistory.push({date:todayKey(),activityId:a.id,score,interaction_type:a.interaction_type,hints:interactionRuntime.hintLevel,attempts:interactionRuntime.attempts});data.questHistory=data.questHistory.slice(-100);if(score>=.65)data.shinyStars++;persist(false);setTimeout(()=>{renderQuest();},200);}else persist(false);}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5);}

function makeQuest(){
 const day=Math.floor(Date.now()/86400000),rotation=['language','logic','science','memory','sel','executive','knowledge'],active=['writing','fine','gross','life','creativity'];
 const requested=['reading','reading','math',rotation[day%rotation.length],active[day%active.length]],used=new Set(),picked=[];
 requested.forEach(domain=>{let candidates=activitiesFor(domain).filter(a=>!used.has(a.interaction_type));if(!candidates.length)candidates=activitiesFor(domain);candidates=candidates.sort((a,b)=>{const sa=getStatus(a.domain,a.skill),sb=getStatus(b.domain,b.skill);const rank=s=>s==='Review Needed'?0:s==='Learning'?1:s==='Developing'?2:s==='Introduced'?3:s==='Not Introduced'?4:s==='Mostly Mastered'?5:6;return rank(sa)-rank(sb)||a.difficulty-b.difficulty});const pick=candidates[(day+picked.length)%Math.max(1,candidates.length)];if(pick){picked.push(pick.id);used.add(pick.interaction_type)}});
 data.quest=picked;data.questDate=todayKey();data.questResults={};persist(false);renderQuest();
}
function renderQuest(){
 const date=document.getElementById('questDate');if(date)date.textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
 const title=document.getElementById('questTitle');if(title)title.textContent=(themes[data.theme]||themes.unicorn).title+' Adventure';
 const h=document.getElementById('questCards');if(!h)return;h.innerHTML='';
 (data.quest||[]).forEach((id,i)=>{const a=activities.find(x=>x.id===id);if(!a)return;const done=data.questResults[id]!=null,b=document.createElement('button');b.className='quest-card child-quest '+(done?'done':'');b.onclick=()=>runActivity(id);b.innerHTML=`<span class="quest-num">${done?'⭐':i+1}</span><span class="quest-icon">${a.character_icon||a.icon}</span><span class="quest-copy"><small>${done?'Shiny star earned':esc(a.character)}</small><b>${esc(a.title)}</b><em>${esc(a.instruction_text)}</em></span><span class="quest-arrow">›</span>`;h.appendChild(b)});updateStats();
}
function refreshQuest(){makeQuest();toast();}
function ensureQuest(){if(!data.quest||data.questDate!==todayKey()||data.quest.length!==5||data.quest.some(id=>!activities.find(a=>a.id===id)))makeQuest();else renderQuest();}

// Rebuild child-visible activity lists with the structured interaction type.
const _openDomain=openDomain;
openDomain=function(id){go('learn');const d=domainById(id),h=document.getElementById('domainDetail');if(!d)return;const acts=activitiesFor(id);h.innerHTML=`<div class="section-title"><h2>${d.icon} ${d.title}</h2><p>${d.desc}</p></div><div class="card"><h3>Skill progression</h3><div class="skill-chip-wrap">${d.skills.map(s=>`<span class="skill-chip ${slug(getStatus(d.id,s))}">${esc(s)}<small>${getStatus(d.id,s)}</small></span>`).join('')}</div></div><div class="section-title"><h2>Interactive missions</h2><p>Every activity has a real interaction.</p></div><div class="activity-grid">${acts.map(a=>`<button class="activity" onclick="runLearningActivity('${a.id}')"><span class="big">${a.character_icon||a.icon}</span><b>${esc(a.title)}</b><p>${esc(a.instruction_text)}</p><small>${a.interaction_type.replaceAll('_',' ')} · ${a.estimated_minutes} min</small></button>`).join('')||'<div class="card">More activities will rotate here.</div>'}</div><div id="learnRunner" class="card runner"></div>`;h.scrollIntoView({behavior:'smooth'});};

setTheme(data.theme);
renderDomains();
ensureQuest();
updateStats();
