(function(){
const SOUND_SET=[
 {l:'m',sound:'mmmm',word:'moon',emoji:'🌙'},{l:'s',sound:'ssss',word:'sun',emoji:'☀️'},{l:'t',sound:'t',word:'top',emoji:'🎩'},{l:'p',sound:'p',word:'pig',emoji:'🐷'},{l:'a',sound:'aaa',word:'apple',emoji:'🍎'},
 {l:'n',sound:'nnnn',word:'nest',emoji:'🪺'},{l:'f',sound:'ffff',word:'fish',emoji:'🐟'},{l:'h',sound:'hhh',word:'hat',emoji:'🧢'},{l:'r',sound:'rrrr',word:'rainbow',emoji:'🌈'},{l:'l',sound:'llll',word:'leaf',emoji:'🍃'}
];
const WORDS=[{word:'map',emoji:'🗺️'},{word:'mat',emoji:'🧘'},{word:'sat',emoji:'⭐'},{word:'sun',emoji:'☀️'},{word:'sit',emoji:'🪑'},{word:'pin',emoji:'📌'},{word:'cat',emoji:'🐱'},{word:'top',emoji:'🔝'}];
let wordIndex=0,placed=[],selectedLetter=null;
function speak(text,rate=.78){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=rate;u.pitch=1.03;u.lang='en-US';window.speechSynthesis.speak(u)}
function soundEntry(ch){return SOUND_SET.find(v=>v.l===ch)}
function speakLetter(ch){const x=soundEntry(ch);speak(x?`${x.sound}. ${x.word} starts with ${x.sound}.`:ch,.72)}
function record(domain,skill,id,score){try{if(typeof recordEvidence==='function')recordEvidence({domain,skill,id},score);if(typeof persist==='function')persist(false)}catch(e){console.warn(e)}}
function ensureZone(){let zone=document.getElementById('kidPlayZone');if(zone)return zone;const home=document.getElementById('home');if(!home)return null;zone=document.createElement('section');zone.id='kidPlayZone';zone.className='kid-play-zone';zone.innerHTML=`
<div class="kid-welcome"><div><span>✨ PLAY & LEARN</span><h2>Choose a magical game</h2><p>Hear it, touch it, move it, build it.</p></div><button class="kid-start" onclick="go('quest')">▶ Start Today's Adventure</button></div>
<div class="kid-launchers">
<button onclick="openKidPlay('sounds')"><span>🔊</span><b>Sound Garden</b><small>Tap letters. Hear sounds.</small></button>
<button onclick="openKidPlay('words')"><span>🔤</span><b>Build Words</b><small>Move letters into place.</small></button>
<button onclick="openKidPlay('numbers')"><span>💎</span><b>Number Magic</b><small>Touch and count pearls.</small></button>
<button onclick="go('quest')"><span>👑</span><b>Princess Quest</b><small>Five mixed missions.</small></button>
</div><div id="kidPlayStage" class="kid-play-stage"></div>`;home.prepend(zone);return zone}
window.openKidPlay=function(mode){const zone=ensureZone(),stage=zone?.querySelector('#kidPlayStage');if(!stage)return;stage.classList.add('open');if(mode==='sounds')renderSounds(stage);if(mode==='words')renderWords(stage);if(mode==='numbers')renderNumbers(stage);stage.scrollIntoView({behavior:'smooth',block:'start'})};
function closeButton(){return `<button class="kid-close" aria-label="Close" onclick="document.getElementById('kidPlayStage').classList.remove('open')">✕</button>`}
function renderSounds(stage){stage.innerHTML=`${closeButton()}<div class="play-title"><span>🦄</span><div><h3>Sound Garden</h3><p>Tap a letter to hear its sound.</p></div></div><div class="sound-garden">${SOUND_SET.map(x=>`<button class="sound-flower" data-letter="${x.l}"><span class="flower-letter">${x.l}</span><span>${x.emoji}</span><small>${x.word}</small></button>`).join('')}</div><div class="play-coach">⭐ Find the sound that starts <b>moon</b>.</div>`;stage.querySelectorAll('.sound-flower').forEach(b=>b.onclick=()=>{b.classList.add('bloom');setTimeout(()=>b.classList.remove('bloom'),420);speakLetter(b.dataset.letter)});}
function currentWord(){return WORDS[wordIndex%WORDS.length]}
function renderWords(stage){placed=[];selectedLetter=null;const w=currentWord();const bank=[...new Set((w.word+'stpnm').split(''))].sort(()=>Math.random()-.5);stage.innerHTML=`${closeButton()}<div class="play-title"><span>👸</span><div><h3>Build the Word</h3><p>Listen. Move each letter.</p></div></div><button class="hear-word" onclick="kidHearWord()">🔊 Hear ${w.word.toUpperCase()}</button><div class="word-picture" aria-hidden="true">${w.emoji}</div><div class="kid-word-slots">${w.word.split('').map((_,i)=>`<button class="kid-slot" data-index="${i}">_</button>`).join('')}</div><div class="kid-letter-bank">${bank.map((l,i)=>`<button class="kid-letter" draggable="true" data-letter="${l}" data-id="${i}">${l}</button>`).join('')}</div><p class="kid-mini-help">Drag a letter, or tap a letter then a box.</p><div id="kidWordFeedback" class="kid-feedback"></div><div class="kid-actions"><button onclick="kidCheckWord()">⭐ Check My Word</button><button onclick="kidResetWord()">↻ Start Over</button></div>`;enableWordDrag(stage);kidHearWord();}
function enableWordDrag(stage){stage.querySelectorAll('.kid-letter').forEach(b=>{b.onclick=()=>{stage.querySelectorAll('.kid-letter').forEach(x=>x.classList.remove('selected'));selectedLetter=b;b.classList.add('selected');speakLetter(b.dataset.letter)};b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.id))});stage.querySelectorAll('.kid-slot').forEach(s=>{s.addEventListener('dragover',e=>e.preventDefault());s.addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');placeLetter(stage.querySelector(`.kid-letter[data-id="${CSS.escape(id)}"]`),s)});s.onclick=()=>{if(selectedLetter)placeLetter(selectedLetter,s)}})}
function placeLetter(letterBtn,slot){if(!letterBtn||!slot)return;const i=+slot.dataset.index;placed[i]=letterBtn.dataset.letter;slot.textContent=letterBtn.dataset.letter;slot.classList.add('filled');letterBtn.classList.remove('selected');selectedLetter=null;speakLetter(letterBtn.dataset.letter)}
window.kidHearWord=function(){const w=currentWord();const sounds=w.word.split('').map(ch=>soundEntry(ch)?.sound||ch).join('. ');speak(`${w.word}. ${sounds}. ${w.word}.`,.7)};
window.kidResetWord=function(){renderWords(document.getElementById('kidPlayStage'))};
window.kidCheckWord=function(){const w=currentWord(),answer=placed.join(''),feedback=document.getElementById('kidWordFeedback');if(answer===w.word){feedback.innerHTML=`<b>⭐ You built ${w.word.toUpperCase()}!</b><span>Each sound matched a letter.</span>`;speak(`You built ${w.word}. Great sound work!`);record('reading','CVC encoding',`free-word-${w.word}`,1);setTimeout(()=>{wordIndex++;renderWords(document.getElementById('kidPlayStage'))},1200)}else{feedback.innerHTML='<b>🌈 Try again.</b><span>Tap each letter and listen to its sound.</span>';speak('Almost. Tap each letter and listen to the sound.');record('reading','CVC encoding',`free-word-${w.word}`,.35)}};
function renderNumbers(stage){const target=3+Math.floor(Math.random()*4);stage.dataset.target=target;stage.innerHTML=`${closeButton()}<div class="play-title"><span>🧜‍♀️</span><div><h3>Mermaid Pearl Magic</h3><p>Put exactly ${target} pearls in the chest.</p></div></div><button class="hear-word" id="hearNumber">🔊 Hear It</button><div class="pearl-bank">${Array.from({length:8},(_,i)=>`<button class="pearl" data-i="${i}">⚪</button>`).join('')}</div><div class="pearl-chest"><span>🧰</span><b>Treasure Chest</b><div id="pearlCount">0 pearls</div></div><div id="numberFeedback" class="kid-feedback"></div><div class="kid-actions"><button onclick="kidCheckNumber()">⭐ Check My Pearls</button><button onclick="openKidPlay('numbers')">↻ New Number</button></div>`;stage.querySelector('#hearNumber').onclick=()=>speak(`Put exactly ${target} pearls in the treasure chest.`);stage.querySelectorAll('.pearl').forEach(p=>p.onclick=()=>{p.classList.toggle('chosen');const n=stage.querySelectorAll('.pearl.chosen').length;document.getElementById('pearlCount').textContent=`${n} pearl${n===1?'':'s'}`;speak(String(n),.72)});speak(`Put exactly ${target} pearls in the treasure chest.`)}
window.kidCheckNumber=function(){const stage=document.getElementById('kidPlayStage'),n=stage.querySelectorAll('.pearl.chosen').length,t=+stage.dataset.target,f=document.getElementById('numberFeedback');if(n===t){f.innerHTML=`<b>⭐ Exactly ${t}!</b><span>You counted the right amount.</span>`;speak(`Yes. Exactly ${t} pearls.`);record('math','One-to-one correspondence',`free-count-${t}`,1)}else{f.innerHTML=`<b>🌈 Count again.</b><span>You have ${n}. You need ${t}.</span>`;speak(`Count again. You have ${n}. You need ${t}.`);record('math','One-to-one correspondence',`free-count-${t}`,.4)}};
ensureZone();
})();