(function(){
let ATLAS='';
const SCENE_POS={fairy:[0,0],unicorn:[1,0],ice:[2,0],seasons:[3,0],coral:[0,1],ocean:[1,1],forest:[2,1],reading:[3,1],cinderella:[0,2],ballroom:[1,2],tea:[2,2],friendship:[3,2]};
const M={fairy:['Rainbow Fairy Castle','motivation and transitions'],unicorn:['Unicorn Princess Rainbow','imagination and story creation'],ice:['Ice Ballroom','listening and memory'],seasons:['Ice Sisters Seasons','weather and compare/contrast'],coral:['Coral Reef Adventure','ocean habitats and counting'],ocean:['Underwater Kingdom','science and observation'],forest:['Forest Friends','animals and categorization'],reading:['Princess Reading Nook','reading and story language'],cinderella:['Cinderella Transformation','before/after and sequencing'],ballroom:['Royal Ballroom Dance','movement sequences'],tea:['Princess Tea Party','counting, manners and sequencing'],friendship:['Friendship Garden','empathy and kindness']};
const T={unicorn:['unicorn','fairy','friendship'],ice:['ice','seasons','ballroom'],mermaid:['coral','ocean','fairy'],library:['reading','forest','friendship'],tower:['cinderella','ballroom','reading'],fairy:['fairy','friendship','unicorn'],space:['fairy','unicorn','ice']};
const D={reading:['reading','fairy'],math:['tea','coral'],language:['friendship','reading'],writing:['reading','fairy'],logic:['cinderella','tea'],science:['ocean','coral','forest'],memory:['ice','seasons'],sel:['friendship','tea'],executive:['cinderella','ballroom'],life:['tea','friendship'],creativity:['unicorn','reading'],fine:['fairy','friendship'],gross:['ballroom','ice'],knowledge:['forest','ocean']};
const A={'read-first':'fairy','read-blend':'unicorn','read-cvc':'reading','read-seg':'fairy','math-compose':'coral','math-qty':'seasons','math-pattern':'seasons','math-add':'tea','language-retell':'cinderella','language-why':'friendship','science-float':'ocean','science-shadow':'fairy','memory-directions':'ice','executive-switch':'ballroom','sel-feelings':'friendship','life-cleanup':'cinderella','creativity-story':'unicorn','fine-sort':'fairy','gross-sequence':'ballroom','knowledge-community':'forest'};
const NO=new Set(['read-first','read-blend','read-cvc','read-seg']), BACKUP='rainbowMagicLearningBackupV3';
function e(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function k(a){if(A[a?.id])return A[a.id];const p=D[a?.domain]||['fairy'];let n=0;for(const c of String(a?.id||''))n=(n*31+c.charCodeAt(0))>>>0;return p[n%p.length]}
function st(x){const p=SCENE_POS[x]||SCENE_POS.fairy;return `background-image:url('${ATLAS}');background-size:400% 300%;background-position:${p[0]*(100/3)}% ${p[1]*50}%;`}
function sp(x,c='scene-sprite'){return `<span class="${c}" role="img" aria-label="${e((M[x]||['Magical learning scene'])[0])}" data-scene="${x}" style="${ATLAS?st(x):''}"></span>`}
function applyAtlas(){document.querySelectorAll('[data-scene]').forEach(el=>el.setAttribute('style',st(el.dataset.scene)))}
async function loadAtlas(){try{const parts=await Promise.all([1,2,3].map(i=>fetch(`./assets/atlas-${i}.b64?v=1`).then(r=>{if(!r.ok)throw new Error('atlas');return r.text()})));ATLAS='data:image/webp;base64,'+parts.join('').replace(/\s/g,'');applyAtlas()}catch(err){console.warn('Learning art could not load',err)}}
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)localStorage.setItem(BACKUP,raw)}catch{}
function hero(){const h=document.querySelector('.hero');if(!h)return;let b=h.querySelector('.hero-visual');if(!b){b=document.createElement('div');b.className='hero-visual';h.appendChild(b)}const x=(T[data?.theme]||T.unicorn)[0];b.innerHTML=sp(x,'hero-sprite')+'<div class="hero-sparkles">✦ ⭐ ✨ ★ ✦</div>'}
function gallery(){let g=document.getElementById('themeGallery');if(!g)return;const p=T[data?.theme]||T.unicorn;g.innerHTML=p.map(x=>`<article class="scene-card">${sp(x)}<div><b>${M[x][0]}</b><small>${M[x][1]}</small></div></article>`).join('')}
function qDecor(){document.querySelectorAll('.quest-card').forEach(c=>{if(c.querySelector('.quest-visual'))return;const a=((typeof activities!=='undefined'&&activities)||[]).find(x=>x.title===c.querySelector('.quest-copy b')?.textContent);if(!a)return;const b=document.createElement('span');b.className='quest-visual';b.innerHTML=sp(k(a),'quest-sprite')+`<span class="quest-icon-badge">${a.character_icon||a.icon||'✨'}</span>`;c.querySelector('.quest-icon')?.replaceWith(b)})}
function dDecor(){document.querySelectorAll('.domain-card').forEach(c=>{if(c.querySelector('.domain-visual'))return;const d=((typeof domains!=='undefined'&&domains)||[]).find(x=>x.title===c.querySelector('.domain-copy b')?.textContent);if(!d)return;const x=(D[d.id]||['fairy'])[0],b=document.createElement('span');b.className='domain-visual';b.innerHTML=sp(x,'domain-sprite')+`<span>${d.icon||'✨'}</span>`;c.querySelector('.domain-icon')?.replaceWith(b)})}
function aDecor(){document.querySelectorAll('.activity').forEach(c=>{if(c.querySelector('.activity-visual'))return;const a=((typeof activities!=='undefined'&&activities)||[]).find(x=>x.title===c.querySelector('b')?.textContent);if(!a)return;const b=document.createElement('span');b.className='activity-visual';b.innerHTML=sp(k(a),'activity-sprite');c.prepend(b)})}
function scene(a,id){if(!a||NO.has(a.id))return;const c=document.getElementById(id),g=c?.querySelector('.character-guide');if(!g||c.querySelector('.learning-scene'))return;const x=k(a);g.insertAdjacentHTML('afterend',`<div class="learning-scene">${sp(x,'learning-sprite')}<div class="learning-scene-label">✨ ${M[x][0]}</div></div>`)}
window.retryCurrentActivity=()=>{const r=(typeof interactionRuntime!=='undefined'?interactionRuntime:null);if(r&&typeof openStructuredActivity==='function')openStructuredActivity(r.activity,r.containerId,r.source)};
function doneBtns(){const f=document.getElementById('structuredFeedback');if(!f||f.querySelector('.after-mission-actions'))return;f.insertAdjacentHTML('beforeend','<div class="after-mission-actions"><button class="retry-mission" onclick="retryCurrentActivity()">↻ Try Again</button><button class="next-mission" onclick="closeStructuredActivity()">⭐ Back to Quest</button></div><div class="retry-note">Retry keeps the first result and adds new practice evidence.</div>')}
function hist(a){return (data.questHistory||[]).filter(x=>x.activityId===a.id).slice(-8)}
function tip(a){const h=hist(a);if(!h.length)return ['new','Try it first; there is not enough evidence yet.'];const avg=h.reduce((n,x)=>n+(+x.score||0),0)/h.length,at=h.reduce((n,x)=>n+(x.attempts||1),0)/h.length,hi=h.reduce((n,x)=>n+(x.hints||0),0)/h.length;if(avg>=.88&&at<1.8&&hi<.6)return ['ready','Strong and efficient. Try a harder example or a different interaction format next.'];if(avg>=.68)return ['practice','Good learning zone. Keep the skill, change the game, and ask her to explain how she knows.'];if(at>=2.5||hi>=1.5)return ['support','Reduce one difficulty step, model one example, then retry with stronger scaffolding.'];return ['support','Repeat this skill in a different format before adding new content.']}
function insights(){const p=document.getElementById('parent');if(!p)return;let b=document.getElementById('learningInsights');if(!b){const t=document.createElement('div');t.className='section-title';t.innerHTML='<h2>📊 Learning Coach Analysis</h2><p>Uses attempts, hints and recent success—not only stars.</p>';b=document.createElement('div');b.id='learningInsights';b.className='insight-grid';p.querySelector('#skillTracker')?.closest('.card')?.after(t,b)}if(!b)return;const l=((typeof activities!=='undefined'&&activities)||[]).filter(a=>hist(a).length).slice(-6);b.innerHTML=l.length?l.map(a=>{const h=hist(a),z=h[h.length-1],r=tip(a);return `<div class="insight-card ${r[0]}"><span>${a.icon||'✨'} ${e(a.skill)}</span><b>${e(a.title)}</b><small>Latest: ${Math.round((z.score||0)*100)}% · attempts ${z.attempts||1} · hints ${z.hints||0}</small><p>${r[1]}</p><button onclick="go('learn');setTimeout(()=>runLearningActivity('${a.id}'),60)">Practice this skill ↻</button></div>`}).join(''):'<div class="card"><b>No practice history yet.</b><p>Complete a few missions and the app will suggest what to repeat, strengthen, or extend.</p></div>'}
function safety(){const p=document.getElementById('parent');if(!p||document.getElementById('dataSafetyTools'))return;const x=document.createElement('div');x.id='dataSafetyTools';x.className='card data-safety';x.innerHTML='<h3>💾 Progress safety</h3><p>Updates preserve this browser’s progress. You can also export a backup before changing devices.</p><div class="row"><button id="exportProgress" class="btn soft">Export Progress</button><label class="btn soft import-label">Import Progress<input id="importProgress" type="file" accept="application/json" hidden></label></div>';p.querySelector('.grid')?.after(x);x.querySelector('#exportProgress').onclick=()=>{const raw=localStorage.getItem(STORAGE_KEY)||JSON.stringify(data),bl=new Blob([raw],{type:'application/json'}),u=URL.createObjectURL(bl),a=document.createElement('a');a.href=u;a.download='rainbow-learning-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};x.querySelector('#importProgress').onchange=v=>{const f=v.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result);localStorage.setItem(BACKUP,localStorage.getItem(STORAGE_KEY)||'{}');localStorage.setItem(STORAGE_KEY,JSON.stringify(o));location.reload()}catch{alert('That backup file could not be read.')}};r.readAsText(f)}}
if(typeof setTheme==='function'){const old=setTheme;window.setTheme=v=>{old(v);hero();gallery()}}
if(typeof renderQuest==='function'){const old=renderQuest;window.renderQuest=()=>{old();qDecor()}}
if(typeof renderDomains==='function'){const old=renderDomains;window.renderDomains=()=>{old();dDecor()}}
if(typeof openDomain==='function'){const old=openDomain;window.openDomain=v=>{old(v);setTimeout(aDecor,0)}}
if(typeof openStructuredActivity==='function'){const old=openStructuredActivity;window.openStructuredActivity=(a,id,src)=>{old(a,id,src);scene(a,id);const t=document.querySelector(`#${id} .child-tools`);if(t&&!t.querySelector('.start-over'))t.insertAdjacentHTML('beforeend','<button class="child-tool start-over" onclick="retryCurrentActivity()">↻ Start Over</button>')}}
if(typeof finishSuccess==='function'){const old=finishSuccess;window.finishSuccess=v=>{old(v);setTimeout(()=>{doneBtns();insights()},0)}}
if(typeof finishAttempt==='function'){const old=finishAttempt;window.finishAttempt=v=>{old(v);setTimeout(()=>{doneBtns();insights()},0)}}
if(typeof go==='function'){const old=go;window.go=v=>{old(v);if(v==='parent')setTimeout(()=>{insights();safety()},0)}}
((typeof activities!=='undefined'&&activities)||[]).forEach(a=>a.visual_policy=NO.has(a.id)?'quest-card-only-no-answer-clue':'context-support');hero();gallery();qDecor();dDecor();aDecor();insights();safety();loadAtlas();
})();
