(function(){
const scenes={
  fairy:{file:'fairy-castle-rainbow.jpg',title:'Rainbow Fairy Castle',use:'motivation and transitions'},
  unicorn:{file:'unicorn-princess-rainbow.webp',title:'Unicorn Princess Rainbow',use:'imagination and story creation'},
  ice:{file:'anna-elsa-ballroom.jpg',title:'Ice Ballroom',use:'listening and memory'},
  seasons:{file:'elsa-anna-seasons.webp',title:'Ice Sisters Seasons',use:'weather and compare/contrast'},
  coral:{file:'ariel-coral-world.webp',title:'Coral Reef Adventure',use:'ocean habitats and counting'},
  ocean:{file:'ariel-underwater.jpg',title:'Underwater Kingdom',use:'science and observation'},
  forest:{file:'snow-white-forest.jpg',title:'Forest Friends',use:'animals and categorization'},
  reading:{file:'jasmine-reading-art.webp',title:'Princess Reading Nook',use:'reading and story language'},
  cinderella:{file:'cinderella-magic-scene.webp',title:'Cinderella Transformation',use:'before/after and sequencing'},
  ballroom:{file:'cinderella-prince-ballroom.webp',title:'Royal Ballroom Dance',use:'movement sequences'},
  tea:{file:'rapunzel-belle-tiana-tea.webp',title:'Princess Tea Party',use:'counting, manners and sequencing'},
  friendship:{file:'princess-friendship-garden.jpg',title:'Friendship Garden',use:'empathy and kindness'}
};
const themesMap={unicorn:['unicorn','fairy','friendship'],ice:['ice','seasons','ballroom'],mermaid:['coral','ocean','fairy'],library:['reading','forest','friendship'],tower:['cinderella','ballroom','reading'],fairy:['fairy','friendship','unicorn'],space:['fairy','unicorn','ice']};
const domainMap={reading:['reading','fairy'],math:['tea','coral'],language:['friendship','reading'],writing:['reading','fairy'],logic:['cinderella','tea'],science:['ocean','coral','forest'],memory:['ice','seasons'],sel:['friendship','tea'],executive:['cinderella','ballroom'],life:['tea','friendship'],creativity:['unicorn','reading'],fine:['fairy','friendship'],gross:['ballroom','ice'],knowledge:['forest','ocean']};
const activityMap={'read-first':'fairy','read-blend':'unicorn','read-cvc':'reading','read-seg':'fairy','math-compose':'coral','math-qty':'seasons','math-pattern':'seasons','math-add':'tea','language-retell':'cinderella','language-why':'friendship','science-float':'ocean','science-shadow':'fairy','memory-directions':'ice','executive-switch':'ballroom','sel-feelings':'friendship','life-cleanup':'cinderella','creativity-story':'unicorn','fine-sort':'fairy','gross-sequence':'ballroom','knowledge-community':'forest'};
const noAnswerClue=new Set(['read-first','read-blend','read-cvc','read-seg']);
const BACKUP='rainbowMagicLearningBackupV3';
function safe(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function listActivities(){return (typeof activities!=='undefined'&&activities)||[]}
function listDomains(){return (typeof domains!=='undefined'&&domains)||[]}
function sceneForActivity(a){if(activityMap[a?.id])return activityMap[a.id];const pool=domainMap[a?.domain]||['fairy'];let n=0;for(const c of String(a?.id||''))n=(n*31+c.charCodeAt(0))>>>0;return pool[n%pool.length]}
function img(key,cls='scene-img'){const s=scenes[key]||scenes.fairy;return `<img class="${cls}" src="./assets/${s.file}" alt="${safe(s.title)}" loading="lazy">`}
function decorateHero(){const hero=document.querySelector('.hero');if(!hero)return;let box=hero.querySelector('.hero-visual');if(!box){box=document.createElement('div');box.className='hero-visual';hero.appendChild(box)}const key=(themesMap[data?.theme]||themesMap.unicorn)[0];box.innerHTML=img(key,'hero-image')+'<div class="hero-sparkles">✦ ⭐ ✨ ★ ✦</div>'}
function ensureGallery(){const home=document.getElementById('home');if(!home)return;let g=document.getElementById('themeGallery');if(!g){const title=document.createElement('div');title.className='section-title';title.innerHTML='<h2>✨ Magical Story Worlds</h2><p>Pictures support attention, language and imagination—not answer guessing.</p>';g=document.createElement('div');g.id='themeGallery';g.className='scene-gallery';const principles=[...home.querySelectorAll('.section-title')].find(x=>x.textContent.includes('Learning principles'));if(principles)principles.before(title,g);else home.append(title,g)}const pool=themesMap[data?.theme]||themesMap.unicorn;g.innerHTML=pool.map(key=>{const s=scenes[key];return `<article class="scene-card">${img(key)}<div><b>${safe(s.title)}</b><small>${safe(s.use)}</small></div></article>`}).join('')}
function decorateQuest(){document.querySelectorAll('.quest-card').forEach(card=>{if(card.querySelector('.quest-visual'))return;const title=card.querySelector('.quest-copy b')?.textContent;const a=listActivities().find(x=>x.title===title);if(!a)return;const key=sceneForActivity(a),box=document.createElement('span');box.className='quest-visual';box.innerHTML=img(key,'quest-image')+`<span class="quest-icon-badge">${a.character_icon||a.icon||'✨'}</span>`;card.querySelector('.quest-icon')?.replaceWith(box)})}
function decorateDomains(){document.querySelectorAll('.domain-card').forEach(card=>{if(card.querySelector('.domain-visual'))return;const title=card.querySelector('.domain-copy b')?.textContent;const d=listDomains().find(x=>x.title===title);if(!d)return;const key=(domainMap[d.id]||['fairy'])[0],box=document.createElement('span');box.className='domain-visual';box.innerHTML=img(key,'domain-image')+`<span>${d.icon||'✨'}</span>`;card.querySelector('.domain-icon')?.replaceWith(box)})}
function decorateActivities(){document.querySelectorAll('.activity').forEach(card=>{if(card.querySelector('.activity-visual'))return;const title=card.querySelector('b')?.textContent;const a=listActivities().find(x=>x.title===title);if(!a)return;const box=document.createElement('span');box.className='activity-visual';box.innerHTML=img(sceneForActivity(a),'activity-image');card.prepend(box)})}
function addLearningScene(a,containerId){if(!a||noAnswerClue.has(a.id))return;const root=document.getElementById(containerId),guide=root?.querySelector('.character-guide');if(!guide||root.querySelector('.learning-scene'))return;const key=sceneForActivity(a),s=scenes[key];guide.insertAdjacentHTML('afterend',`<div class="learning-scene">${img(key,'learning-image')}<div class="learning-scene-label">✨ ${safe(s.title)}</div></div>`)}
function historyFor(a){return (data.questHistory||[]).filter(x=>x.activityId===a.id).slice(-8)}
function adviceFor(a){const h=historyFor(a);if(!h.length)return ['new','Try it first; there is not enough evidence yet.'];const avg=h.reduce((n,x)=>n+(+x.score||0),0)/h.length,attempts=h.reduce((n,x)=>n+(x.attempts||1),0)/h.length,hints=h.reduce((n,x)=>n+(x.hints||0),0)/h.length;if(avg>=.88&&attempts<1.8&&hints<.6)return ['ready','Strong and efficient. Try a harder example or the same skill in a different interaction format.'];if(avg>=.68)return ['practice','This is a productive learning zone. Keep the skill, change the game, and ask her to explain how she knows.'];if(attempts>=2.5||hints>=1.5)return ['support','Reduce one difficulty step, model one example, then retry with stronger scaffolding.'];return ['support','Repeat the same skill in a different format before adding new content.']}
function renderInsights(){const parent=document.getElementById('parent');if(!parent)return;let grid=document.getElementById('learningInsights');if(!grid){const title=document.createElement('div');title.className='section-title';title.innerHTML='<h2>📊 Learning Coach Analysis</h2><p>Uses success, retries and hints to suggest the next move.</p>';grid=document.createElement('div');grid.id='learningInsights';grid.className='insight-grid';parent.querySelector('#skillTracker')?.closest('.card')?.after(title,grid)}const recent=listActivities().filter(a=>historyFor(a).length).slice(-6);grid.innerHTML=recent.length?recent.map(a=>{const h=historyFor(a),last=h[h.length-1],adv=adviceFor(a);return `<div class="insight-card ${adv[0]}"><span>${a.icon||'✨'} ${safe(a.skill)}</span><b>${safe(a.title)}</b><small>Latest ${Math.round((last.score||0)*100)}% · ${last.attempts||1} attempt(s) · ${last.hints||0} hint(s)</small><p>${safe(adv[1])}</p><button onclick="go('learn');setTimeout(()=>runLearningActivity('${a.id}'),80)">Practice this skill ↻</button></div>`}).join(''):'<div class="card"><b>No practice history yet.</b><p>Complete a few missions and the app will recommend what to repeat, strengthen, or extend.</p></div>'}
function ensureProgressTools(){const parent=document.getElementById('parent');if(!parent||document.getElementById('dataSafetyTools'))return;const box=document.createElement('div');box.id='dataSafetyTools';box.className='card data-safety';box.innerHTML='<h3>💾 Progress safety</h3><p>App updates preserve progress in this browser. Export a backup before switching devices or clearing Safari data.</p><div class="row"><button id="exportProgress" class="btn soft">Export Progress</button><label class="btn soft import-label">Import Progress<input id="importProgress" type="file" accept="application/json" hidden></label></div>';parent.querySelector('.grid')?.after(box);box.querySelector('#exportProgress').onclick=()=>{const raw=localStorage.getItem(STORAGE_KEY)||JSON.stringify(data),blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='rainbow-learning-progress.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),500)};box.querySelector('#importProgress').onchange=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);localStorage.setItem(BACKUP,localStorage.getItem(STORAGE_KEY)||'{}');localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));location.reload()}catch{alert('That progress backup could not be read.')}};reader.readAsText(file)}}
window.retryCurrentActivity=()=>{const r=(typeof interactionRuntime!=='undefined'?interactionRuntime:null);if(r&&typeof openStructuredActivity==='function')openStructuredActivity(r.activity,r.containerId,r.source)};
function addCompletionActions(){const feedback=document.getElementById('structuredFeedback');if(!feedback||feedback.querySelector('.after-mission-actions'))return;feedback.insertAdjacentHTML('beforeend','<div class="after-mission-actions"><button class="retry-mission" onclick="retryCurrentActivity()">↻ Try Again</button><button class="next-mission" onclick="closeStructuredActivity()">⭐ Back to Quest</button></div><div class="retry-note">Retry keeps the earlier result and adds another piece of learning evidence.</div>')}
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)localStorage.setItem(BACKUP,raw)}catch{}
if(typeof setTheme==='function'){const original=setTheme;window.setTheme=v=>{original(v);decorateHero();ensureGallery()}}
if(typeof renderQuest==='function'){const original=renderQuest;window.renderQuest=()=>{original();decorateQuest()}}
if(typeof renderDomains==='function'){const original=renderDomains;window.renderDomains=()=>{original();decorateDomains()}}
if(typeof openDomain==='function'){const original=openDomain;window.openDomain=v=>{original(v);setTimeout(decorateActivities,0)}}
if(typeof openStructuredActivity==='function'){const original=openStructuredActivity;window.openStructuredActivity=(a,id,source)=>{original(a,id,source);addLearningScene(a,id);const tools=document.querySelector(`#${id} .child-tools`);if(tools&&!tools.querySelector('.start-over'))tools.insertAdjacentHTML('beforeend','<button class="child-tool start-over" onclick="retryCurrentActivity()">↻ Start Over</button>')}}
if(typeof finishSuccess==='function'){const original=finishSuccess;window.finishSuccess=v=>{original(v);setTimeout(()=>{addCompletionActions();renderInsights()},0)}}
if(typeof finishAttempt==='function'){const original=finishAttempt;window.finishAttempt=v=>{original(v);setTimeout(()=>{addCompletionActions();renderInsights()},0)}}
if(typeof go==='function'){const original=go;window.go=v=>{original(v);if(v==='parent')setTimeout(()=>{renderInsights();ensureProgressTools()},0)}}
listActivities().forEach(a=>a.visual_policy=noAnswerClue.has(a.id)?'quest-card-only-no-answer-clue':'context-support');
decorateHero();ensureGallery();decorateQuest();decorateDomains();decorateActivities();renderInsights();ensureProgressTools();
})();
